// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: coreapi/model/block.proto

package model

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of content block.
// TEXT and CODE are leaf types that hold text in `value`.
// BULLETS is a container type that holds child blocks in `blocks`.
type Block_BlockType int32

const (
	Block_BLOCK_TYPE_UNSPECIFIED Block_BlockType = 0
	// Container for nested child blocks forming a bullet list.
	Block_BLOCK_TYPE_BULLETS Block_BlockType = 1
	// Code snippet with optional syntax highlighting via `language`.
	Block_BLOCK_TYPE_CODE Block_BlockType = 2
	// Rich text content with inline markup support.
	Block_BLOCK_TYPE_TEXT Block_BlockType = 3
)

// Enum value maps for Block_BlockType.
var (
	Block_BlockType_name = map[int32]string{
		0: "BLOCK_TYPE_UNSPECIFIED",
		1: "BLOCK_TYPE_BULLETS",
		2: "BLOCK_TYPE_CODE",
		3: "BLOCK_TYPE_TEXT",
	}
	Block_BlockType_value = map[string]int32{
		"BLOCK_TYPE_UNSPECIFIED": 0,
		"BLOCK_TYPE_BULLETS":     1,
		"BLOCK_TYPE_CODE":        2,
		"BLOCK_TYPE_TEXT":        3,
	}
)

func (x Block_BlockType) Enum() *Block_BlockType {
	p := new(Block_BlockType)
	*p = x
	return p
}

func (x Block_BlockType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Block_BlockType) Descriptor() protoreflect.EnumDescriptor {
	return file_coreapi_model_block_proto_enumTypes[0].Descriptor()
}

func (Block_BlockType) Type() protoreflect.EnumType {
	return &file_coreapi_model_block_proto_enumTypes[0]
}

func (x Block_BlockType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Block_BlockType.Descriptor instead.
func (Block_BlockType) EnumDescriptor() ([]byte, []int) {
	return file_coreapi_model_block_proto_rawDescGZIP(), []int{0, 0}
}

// Block represents a structured content block within a message.
// Blocks can be nested to form bullet lists.
type Block struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content block type that determines how the block is rendered and which fields are applicable.
	//
	// +kubebuilder:validation:Required
	Type Block_BlockType `protobuf:"varint,1,opt,name=type,proto3,enum=coreapi.model.Block_BlockType" json:"type,omitempty"`
	// Programming language identifier for syntax highlighting.
	// Only applicable when type is CODE.
	//
	// +kubebuilder:validation:Nullable
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	// Text content of the block.
	// Applicable for TEXT and CODE block types; ignored for BULLETS.
	//
	// +kubebuilder:validation:Nullable
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Nested child blocks that form a hierarchical list structure.
	// Only applicable when type is BULLETS; must be omitted for leaf types (TEXT, CODE).
	//
	// +kubebuilder:validation:Nullable
	Blocks        []*Block `protobuf:"bytes,4,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_coreapi_model_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_coreapi_model_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_coreapi_model_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetType() Block_BlockType {
	if x != nil {
		return x.Type
	}
	return Block_BLOCK_TYPE_UNSPECIFIED
}

func (x *Block) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Block) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Block) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

var File_coreapi_model_block_proto protoreflect.FileDescriptor

const file_coreapi_model_block_proto_rawDesc = "" +
	"\n" +
	"\x19coreapi/model/block.proto\x12\rcoreapi.model\x1a\x1bbuf/validate/validate.proto\"\x8e\x02\n" +
	"\x05Block\x12:\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.coreapi.model.Block.BlockTypeB\x06\xbaH\x03\xc8\x01\x01R\x04type\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12,\n" +
	"\x06blocks\x18\x04 \x03(\v2\x14.coreapi.model.BlockR\x06blocks\"i\n" +
	"\tBlockType\x12\x1a\n" +
	"\x16BLOCK_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12BLOCK_TYPE_BULLETS\x10\x01\x12\x13\n" +
	"\x0fBLOCK_TYPE_CODE\x10\x02\x12\x13\n" +
	"\x0fBLOCK_TYPE_TEXT\x10\x03Bb\n" +
	"&io.channel.api.proto.pub.coreapi.modelP\x01Z6github.com/channel-io/ch-proto-public/coreapi/go/modelb\x06proto3"

var (
	file_coreapi_model_block_proto_rawDescOnce sync.Once
	file_coreapi_model_block_proto_rawDescData []byte
)

func file_coreapi_model_block_proto_rawDescGZIP() []byte {
	file_coreapi_model_block_proto_rawDescOnce.Do(func() {
		file_coreapi_model_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coreapi_model_block_proto_rawDesc), len(file_coreapi_model_block_proto_rawDesc)))
	})
	return file_coreapi_model_block_proto_rawDescData
}

var file_coreapi_model_block_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_coreapi_model_block_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_coreapi_model_block_proto_goTypes = []any{
	(Block_BlockType)(0), // 0: coreapi.model.Block.BlockType
	(*Block)(nil),        // 1: coreapi.model.Block
}
var file_coreapi_model_block_proto_depIdxs = []int32{
	0, // 0: coreapi.model.Block.type:type_name -> coreapi.model.Block.BlockType
	1, // 1: coreapi.model.Block.blocks:type_name -> coreapi.model.Block
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_coreapi_model_block_proto_init() }
func file_coreapi_model_block_proto_init() {
	if File_coreapi_model_block_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coreapi_model_block_proto_rawDesc), len(file_coreapi_model_block_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coreapi_model_block_proto_goTypes,
		DependencyIndexes: file_coreapi_model_block_proto_depIdxs,
		EnumInfos:         file_coreapi_model_block_proto_enumTypes,
		MessageInfos:      file_coreapi_model_block_proto_msgTypes,
	}.Build()
	File_coreapi_model_block_proto = out.File
	file_coreapi_model_block_proto_goTypes = nil
	file_coreapi_model_block_proto_depIdxs = nil
}
