// Code generated by protoc-gen-go-canonical-enum-namings. DO NOT EDIT.

package model

// GetString returns the canonical string for SessionWatch.
func (x SessionWatch) GetString() string {
	switch x {
	case SessionWatch_SESSION_WATCH_ALL:
		return "all"
	case SessionWatch_SESSION_WATCH_INFO:
		return "info"
	case SessionWatch_SESSION_WATCH_NONE:
		return "none"
	default:
		return ""
	}
}

// SessionWatchForString returns the SessionWatch enum for the given canonical string.
func SessionWatchForString(value string) SessionWatch {
	switch value {
	case "all":
		return SessionWatch_SESSION_WATCH_ALL
	case "info":
		return SessionWatch_SESSION_WATCH_INFO
	case "none":
		return SessionWatch_SESSION_WATCH_NONE
	default:
		return SessionWatch_SESSION_WATCH_UNSPECIFIED
	}
}

