// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: coreapi/model/event.proto

package model

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event represents a user-level tracking event.
// Events capture user actions such as page views, purchases, and custom interactions.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique event identifier.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of the user who triggered the event.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Channel ID this event belongs to.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	ChannelId string `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// Event name identifying the type of action.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=64
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Custom properties associated with the event.
	//
	// +kubebuilder:validation:Nullable
	Property *structpb.Struct `protobuf:"bytes,5,opt,name=property,proto3" json:"property,omitempty"`
	// Event creation timestamp.
	//
	// +kubebuilder:validation:Required
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Event expiration timestamp.
	//
	// +kubebuilder:validation:Nullable
	ExpireAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	// Event data version number.
	//
	// +kubebuilder:validation:Nullable
	Version       int64 `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_coreapi_model_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_coreapi_model_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_coreapi_model_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Event) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetProperty() *structpb.Struct {
	if x != nil {
		return x.Property
	}
	return nil
}

func (x *Event) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Event) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

func (x *Event) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_coreapi_model_event_proto protoreflect.FileDescriptor

const file_coreapi_model_event_proto_rawDesc = "" +
	"\n" +
	"\x19coreapi/model/event.proto\x12\rcoreapi.model\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x05\n" +
	"\x05Event\x12]\n" +
	"\x02id\x18\x01 \x01(\tBM\xbaHJ\xba\x01D\n" +
	"\rstring.minLen\x12\"value must be at least 1 character\x1a\x0fsize(this) >= 1\xc8\x01\x01R\x02id\x12f\n" +
	"\auser_id\x18\x02 \x01(\tBM\xbaHJ\xba\x01D\n" +
	"\rstring.minLen\x12\"value must be at least 1 character\x1a\x0fsize(this) >= 1\xc8\x01\x01R\x06userId\x12l\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tBM\xbaHJ\xba\x01D\n" +
	"\rstring.minLen\x12\"value must be at least 1 character\x1a\x0fsize(this) >= 1\xc8\x01\x01R\tchannelId\x12\xb1\x01\n" +
	"\x04name\x18\x04 \x01(\tB\x9c\x01\xbaH\x98\x01\xba\x01D\n" +
	"\rstring.minLen\x12\"value must be at least 1 character\x1a\x0fsize(this) >= 1\xba\x01K\n" +
	"\rstring.maxLen\x12(value must be no more than 64 characters\x1a\x10size(this) <= 64\xc8\x01\x01R\x04name\x123\n" +
	"\bproperty\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bproperty\x12A\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tcreatedAt\x127\n" +
	"\texpire_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\x12\x18\n" +
	"\aversion\x18\b \x01(\x03R\aversionBb\n" +
	"&io.channel.api.proto.pub.coreapi.modelP\x01Z6github.com/channel-io/ch-proto-public/coreapi/go/modelb\x06proto3"

var (
	file_coreapi_model_event_proto_rawDescOnce sync.Once
	file_coreapi_model_event_proto_rawDescData []byte
)

func file_coreapi_model_event_proto_rawDescGZIP() []byte {
	file_coreapi_model_event_proto_rawDescOnce.Do(func() {
		file_coreapi_model_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coreapi_model_event_proto_rawDesc), len(file_coreapi_model_event_proto_rawDesc)))
	})
	return file_coreapi_model_event_proto_rawDescData
}

var file_coreapi_model_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_coreapi_model_event_proto_goTypes = []any{
	(*Event)(nil),                 // 0: coreapi.model.Event
	(*structpb.Struct)(nil),       // 1: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_coreapi_model_event_proto_depIdxs = []int32{
	1, // 0: coreapi.model.Event.property:type_name -> google.protobuf.Struct
	2, // 1: coreapi.model.Event.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: coreapi.model.Event.expire_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_coreapi_model_event_proto_init() }
func file_coreapi_model_event_proto_init() {
	if File_coreapi_model_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coreapi_model_event_proto_rawDesc), len(file_coreapi_model_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coreapi_model_event_proto_goTypes,
		DependencyIndexes: file_coreapi_model_event_proto_depIdxs,
		MessageInfos:      file_coreapi_model_event_proto_msgTypes,
	}.Build()
	File_coreapi_model_event_proto = out.File
	file_coreapi_model_event_proto_goTypes = nil
	file_coreapi_model_event_proto_depIdxs = nil
}
