// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: coreapi/model/message_content.proto

package model

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message option flags that modify message delivery and display behavior.
type MessageOption int32

const (
	MessageOption_MESSAGE_OPTION_UNSPECIFIED MessageOption = 0
	// Deliver the message as if sent by a manager instead of a bot.
	MessageOption_MESSAGE_OPTION_ACT_AS_MANAGER MessageOption = 1
	// Display the bot as the channel identity instead of its own profile.
	MessageOption_MESSAGE_OPTION_DISPLAY_AS_CHANNEL MessageOption = 2
	// Do not post the message to the chat timeline.
	MessageOption_MESSAGE_OPTION_DO_NOT_POST MessageOption = 3
	// Exclude the message from search results.
	MessageOption_MESSAGE_OPTION_DO_NOT_SEARCH MessageOption = 4
	// Do not deliver the message via app push notification.
	MessageOption_MESSAGE_OPTION_DO_NOT_SEND_APP MessageOption = 5
	// Do not update the Desk inbox timestamp for this message.
	MessageOption_MESSAGE_OPTION_DO_NOT_UPDATE_DESK MessageOption = 6
	// Prevent the message from being edited or deleted after sending.
	MessageOption_MESSAGE_OPTION_IMMUTABLE MessageOption = 7
	// Mark the message as a private internal note visible only to managers.
	MessageOption_MESSAGE_OPTION_PRIVATE MessageOption = 8
	// Suppress all notifications for this message.
	MessageOption_MESSAGE_OPTION_SILENT MessageOption = 9
	// Suppress notifications to managers only.
	MessageOption_MESSAGE_OPTION_SILENT_TO_MANAGER MessageOption = 10
	// Suppress notifications to the user only.
	MessageOption_MESSAGE_OPTION_SILENT_TO_USER MessageOption = 11
	// Send an alert notification to the message writer.
	MessageOption_MESSAGE_OPTION_ALERT_TO_WRITER MessageOption = 12
)

// Enum value maps for MessageOption.
var (
	MessageOption_name = map[int32]string{
		0:  "MESSAGE_OPTION_UNSPECIFIED",
		1:  "MESSAGE_OPTION_ACT_AS_MANAGER",
		2:  "MESSAGE_OPTION_DISPLAY_AS_CHANNEL",
		3:  "MESSAGE_OPTION_DO_NOT_POST",
		4:  "MESSAGE_OPTION_DO_NOT_SEARCH",
		5:  "MESSAGE_OPTION_DO_NOT_SEND_APP",
		6:  "MESSAGE_OPTION_DO_NOT_UPDATE_DESK",
		7:  "MESSAGE_OPTION_IMMUTABLE",
		8:  "MESSAGE_OPTION_PRIVATE",
		9:  "MESSAGE_OPTION_SILENT",
		10: "MESSAGE_OPTION_SILENT_TO_MANAGER",
		11: "MESSAGE_OPTION_SILENT_TO_USER",
		12: "MESSAGE_OPTION_ALERT_TO_WRITER",
	}
	MessageOption_value = map[string]int32{
		"MESSAGE_OPTION_UNSPECIFIED":        0,
		"MESSAGE_OPTION_ACT_AS_MANAGER":     1,
		"MESSAGE_OPTION_DISPLAY_AS_CHANNEL": 2,
		"MESSAGE_OPTION_DO_NOT_POST":        3,
		"MESSAGE_OPTION_DO_NOT_SEARCH":      4,
		"MESSAGE_OPTION_DO_NOT_SEND_APP":    5,
		"MESSAGE_OPTION_DO_NOT_UPDATE_DESK": 6,
		"MESSAGE_OPTION_IMMUTABLE":          7,
		"MESSAGE_OPTION_PRIVATE":            8,
		"MESSAGE_OPTION_SILENT":             9,
		"MESSAGE_OPTION_SILENT_TO_MANAGER":  10,
		"MESSAGE_OPTION_SILENT_TO_USER":     11,
		"MESSAGE_OPTION_ALERT_TO_WRITER":    12,
	}
)

func (x MessageOption) Enum() *MessageOption {
	p := new(MessageOption)
	*p = x
	return p
}

func (x MessageOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageOption) Descriptor() protoreflect.EnumDescriptor {
	return file_coreapi_model_message_content_proto_enumTypes[0].Descriptor()
}

func (MessageOption) Type() protoreflect.EnumType {
	return &file_coreapi_model_message_content_proto_enumTypes[0]
}

func (x MessageOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageOption.Descriptor instead.
func (MessageOption) EnumDescriptor() ([]byte, []int) {
	return file_coreapi_model_message_content_proto_rawDescGZIP(), []int{0}
}

// MessageContent represents the content payload for sending a message via the API.
type MessageContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Structured content blocks of the message.
	//
	// +kubebuilder:validation:Nullable
	Blocks []*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	// Plain text representation of the message.
	//
	// +kubebuilder:validation:Nullable
	PlainText string `protobuf:"bytes,2,opt,name=plain_text,json=plainText,proto3" json:"plain_text,omitempty"`
	// Interactive buttons attached to the message.
	//
	// +kubebuilder:validation:Nullable
	// +kubebuilder:validation:MaxItems=2
	Buttons []*MessageButton `protobuf:"bytes,3,rep,name=buttons,proto3" json:"buttons,omitempty"`
	// File attachments included in the message.
	//
	// +kubebuilder:validation:Nullable
	// +kubebuilder:validation:MaxItems=10
	Files []*MessageFile `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	// Web page link preview attached to the message.
	//
	// +kubebuilder:validation:Nullable
	WebPage *MessageWebPage `protobuf:"bytes,5,opt,name=web_page,json=webPage,proto3" json:"web_page,omitempty"`
	// Interactive form attached to the message.
	// The structure depends on the form type (custom, followUp, call).
	//
	// +kubebuilder:validation:Nullable
	Form *structpb.Struct `protobuf:"bytes,6,opt,name=form,proto3" json:"form,omitempty"`
	// Option flags that modify message delivery and display behavior.
	//
	// +kubebuilder:validation:Nullable
	Options []MessageOption `protobuf:"varint,7,rep,packed,name=options,proto3,enum=coreapi.model.MessageOption" json:"options,omitempty"`
	// Client-generated request identifier for idempotency.
	//
	// +kubebuilder:validation:Nullable
	RequestId     string `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageContent) Reset() {
	*x = MessageContent{}
	mi := &file_coreapi_model_message_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContent) ProtoMessage() {}

func (x *MessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_coreapi_model_message_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContent.ProtoReflect.Descriptor instead.
func (*MessageContent) Descriptor() ([]byte, []int) {
	return file_coreapi_model_message_content_proto_rawDescGZIP(), []int{0}
}

func (x *MessageContent) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *MessageContent) GetPlainText() string {
	if x != nil {
		return x.PlainText
	}
	return ""
}

func (x *MessageContent) GetButtons() []*MessageButton {
	if x != nil {
		return x.Buttons
	}
	return nil
}

func (x *MessageContent) GetFiles() []*MessageFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *MessageContent) GetWebPage() *MessageWebPage {
	if x != nil {
		return x.WebPage
	}
	return nil
}

func (x *MessageContent) GetForm() *structpb.Struct {
	if x != nil {
		return x.Form
	}
	return nil
}

func (x *MessageContent) GetOptions() []MessageOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *MessageContent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_coreapi_model_message_content_proto protoreflect.FileDescriptor

const file_coreapi_model_message_content_proto_rawDesc = "" +
	"\n" +
	"#coreapi/model/message_content.proto\x12\rcoreapi.model\x1a\x1bbuf/validate/validate.proto\x1a\x19coreapi/model/block.proto\x1a\"coreapi/model/message_button.proto\x1a coreapi/model/message_file.proto\x1a$coreapi/model/message_web_page.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x99\x03\n" +
	"\x0eMessageContent\x12,\n" +
	"\x06blocks\x18\x01 \x03(\v2\x14.coreapi.model.BlockR\x06blocks\x12\x1d\n" +
	"\n" +
	"plain_text\x18\x02 \x01(\tR\tplainText\x12@\n" +
	"\abuttons\x18\x03 \x03(\v2\x1c.coreapi.model.MessageButtonB\b\xbaH\x05\x92\x01\x02\x10\x02R\abuttons\x12:\n" +
	"\x05files\x18\x04 \x03(\v2\x1a.coreapi.model.MessageFileB\b\xbaH\x05\x92\x01\x02\x10\n" +
	"R\x05files\x128\n" +
	"\bweb_page\x18\x05 \x01(\v2\x1d.coreapi.model.MessageWebPageR\awebPage\x12+\n" +
	"\x04form\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04form\x126\n" +
	"\aoptions\x18\a \x03(\x0e2\x1c.coreapi.model.MessageOptionR\aoptions\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestId*\xc8\x03\n" +
	"\rMessageOption\x12\x1e\n" +
	"\x1aMESSAGE_OPTION_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dMESSAGE_OPTION_ACT_AS_MANAGER\x10\x01\x12%\n" +
	"!MESSAGE_OPTION_DISPLAY_AS_CHANNEL\x10\x02\x12\x1e\n" +
	"\x1aMESSAGE_OPTION_DO_NOT_POST\x10\x03\x12 \n" +
	"\x1cMESSAGE_OPTION_DO_NOT_SEARCH\x10\x04\x12\"\n" +
	"\x1eMESSAGE_OPTION_DO_NOT_SEND_APP\x10\x05\x12%\n" +
	"!MESSAGE_OPTION_DO_NOT_UPDATE_DESK\x10\x06\x12\x1c\n" +
	"\x18MESSAGE_OPTION_IMMUTABLE\x10\a\x12\x1a\n" +
	"\x16MESSAGE_OPTION_PRIVATE\x10\b\x12\x19\n" +
	"\x15MESSAGE_OPTION_SILENT\x10\t\x12$\n" +
	" MESSAGE_OPTION_SILENT_TO_MANAGER\x10\n" +
	"\x12!\n" +
	"\x1dMESSAGE_OPTION_SILENT_TO_USER\x10\v\x12\"\n" +
	"\x1eMESSAGE_OPTION_ALERT_TO_WRITER\x10\fBb\n" +
	"&io.channel.api.proto.pub.coreapi.modelP\x01Z6github.com/channel-io/ch-proto-public/coreapi/go/modelb\x06proto3"

var (
	file_coreapi_model_message_content_proto_rawDescOnce sync.Once
	file_coreapi_model_message_content_proto_rawDescData []byte
)

func file_coreapi_model_message_content_proto_rawDescGZIP() []byte {
	file_coreapi_model_message_content_proto_rawDescOnce.Do(func() {
		file_coreapi_model_message_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coreapi_model_message_content_proto_rawDesc), len(file_coreapi_model_message_content_proto_rawDesc)))
	})
	return file_coreapi_model_message_content_proto_rawDescData
}

var file_coreapi_model_message_content_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_coreapi_model_message_content_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_coreapi_model_message_content_proto_goTypes = []any{
	(MessageOption)(0),      // 0: coreapi.model.MessageOption
	(*MessageContent)(nil),  // 1: coreapi.model.MessageContent
	(*Block)(nil),           // 2: coreapi.model.Block
	(*MessageButton)(nil),   // 3: coreapi.model.MessageButton
	(*MessageFile)(nil),     // 4: coreapi.model.MessageFile
	(*MessageWebPage)(nil),  // 5: coreapi.model.MessageWebPage
	(*structpb.Struct)(nil), // 6: google.protobuf.Struct
}
var file_coreapi_model_message_content_proto_depIdxs = []int32{
	2, // 0: coreapi.model.MessageContent.blocks:type_name -> coreapi.model.Block
	3, // 1: coreapi.model.MessageContent.buttons:type_name -> coreapi.model.MessageButton
	4, // 2: coreapi.model.MessageContent.files:type_name -> coreapi.model.MessageFile
	5, // 3: coreapi.model.MessageContent.web_page:type_name -> coreapi.model.MessageWebPage
	6, // 4: coreapi.model.MessageContent.form:type_name -> google.protobuf.Struct
	0, // 5: coreapi.model.MessageContent.options:type_name -> coreapi.model.MessageOption
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_coreapi_model_message_content_proto_init() }
func file_coreapi_model_message_content_proto_init() {
	if File_coreapi_model_message_content_proto != nil {
		return
	}
	file_coreapi_model_block_proto_init()
	file_coreapi_model_message_button_proto_init()
	file_coreapi_model_message_file_proto_init()
	file_coreapi_model_message_web_page_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coreapi_model_message_content_proto_rawDesc), len(file_coreapi_model_message_content_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coreapi_model_message_content_proto_goTypes,
		DependencyIndexes: file_coreapi_model_message_content_proto_depIdxs,
		EnumInfos:         file_coreapi_model_message_content_proto_enumTypes,
		MessageInfos:      file_coreapi_model_message_content_proto_msgTypes,
	}.Build()
	File_coreapi_model_message_content_proto = out.File
	file_coreapi_model_message_content_proto_goTypes = nil
	file_coreapi_model_message_content_proto_depIdxs = nil
}
