package main

import (
	"fmt"
	"io"
	"log"
	"os"
	"strings"

	plugin "github.com/golang/protobuf/protoc-gen-go/plugin"
	"github.com/iancoleman/strcase"
	"github.com/samber/lo"
	"golang.org/x/exp/slices"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

var logger = log.Default()

func watermark() string {
	return "// Code generated by protoc-gen-go-canonical-enum-namings. DO NOT EDIT.\n\n"
}

// extractEnumMappings extracts proto enum value name → canonical name (lowerCamel) mappings.
// Matches the convention used by protoc-gen-java-canonical-enum-namings.
func extractEnumMappings(
	protoFile *descriptorpb.FileDescriptorProto,
	enum *descriptorpb.EnumDescriptorProto,
) (string, map[string]string, error) {
	prefix := strcase.ToScreamingSnake(*enum.Name) + "_"
	unspecified := prefix + "UNSPECIFIED"

	if enum.Value[0].Name == nil {
		return "", nil, fmt.Errorf("zero value of enum %s.%s is not specified", *protoFile.Package, *enum.Name)
	}

	if *enum.Value[0].Name != unspecified {
		return "", nil, fmt.Errorf("zero value of enum %s.%s is not %s", *protoFile.Package, *enum.Name, unspecified)
	}

	mapping := map[string]string{}
	for _, value := range enum.Value {
		protoName := *value.Name

		if !strings.HasPrefix(protoName, prefix) {
			return "", nil, fmt.Errorf("enum value %s.%s.%s does not have prefix %s", *protoFile.Package, *enum.Name, protoName, prefix)
		}

		canonicalName := strcase.ToLowerCamel(strings.ReplaceAll(protoName, prefix, ""))
		if protoName != unspecified {
			mapping[canonicalName] = protoName
		}
	}

	return unspecified, mapping, nil
}

// generateGoFile generates a Go file with GetString()/ForString() methods for each enum.
func generateGoFile(
	protoFile *descriptorpb.FileDescriptorProto,
	enums []*descriptorpb.EnumDescriptorProto,
	goPackage string,
) (string, error) {
	var b strings.Builder

	b.WriteString(watermark())
	b.WriteString(fmt.Sprintf("package %s\n\n", goPackage))

	for _, enum := range enums {
		unspecified, mapping, err := extractEnumMappings(protoFile, enum)
		if err != nil {
			return "", err
		}

		canonicalNames := lo.Keys(mapping)
		slices.Sort(canonicalNames)

		// Generate GetString() method — enum → canonical string
		b.WriteString(fmt.Sprintf("// GetString returns the canonical string for %s.\n", *enum.Name))
		b.WriteString(fmt.Sprintf("func (x %s) GetString() string {\n", *enum.Name))
		b.WriteString("\tswitch x {\n")
		for _, canonicalName := range canonicalNames {
			b.WriteString(fmt.Sprintf("\tcase %s_%s:\n", *enum.Name, mapping[canonicalName]))
			b.WriteString(fmt.Sprintf("\t\treturn %q\n", canonicalName))
		}
		b.WriteString("\tdefault:\n")
		b.WriteString("\t\treturn \"\"\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")

		// Generate ForString() function — canonical string → enum
		b.WriteString(fmt.Sprintf("// %sForString returns the %s enum for the given canonical string.\n", *enum.Name, *enum.Name))
		b.WriteString(fmt.Sprintf("func %sForString(value string) %s {\n", *enum.Name, *enum.Name))
		b.WriteString("\tswitch value {\n")
		for _, canonicalName := range canonicalNames {
			b.WriteString(fmt.Sprintf("\tcase %q:\n", canonicalName))
			b.WriteString(fmt.Sprintf("\t\treturn %s_%s\n", *enum.Name, mapping[canonicalName]))
		}
		b.WriteString("\tdefault:\n")
		b.WriteString(fmt.Sprintf("\t\treturn %s_%s\n", *enum.Name, unspecified))
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")
	}

	return b.String(), nil
}

func process(req *plugin.CodeGeneratorRequest, resp *plugin.CodeGeneratorResponse) error {
	logger.Println("Applying go-canonical-enum-namings plugin ...")

	resp.SupportedFeatures = proto.Uint64(uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL))

	for _, protoFile := range req.GetProtoFile() {
		if !lo.Contains(req.FileToGenerate, *protoFile.Name) {
			continue
		}

		enums := protoFile.GetEnumType()
		if len(enums) == 0 {
			continue
		}

		// Derive Go package name from go_package option
		goPackageFull := protoFile.GetOptions().GetGoPackage()
		if goPackageFull == "" {
			continue
		}

		// go_package = "github.com/channel-io/ch-proto-public/coreapi/go/model" → "model"
		parts := strings.Split(goPackageFull, "/")
		goPackage := parts[len(parts)-1]

		// Output path: same as protoc-gen-go output, with _enum_canonical.go suffix
		// e.g. coreapi/go/model/group_enum_canonical.go
		protoFileName := *protoFile.Name
		// coreapi/model/group.proto → group
		baseName := strings.TrimSuffix(protoFileName[strings.LastIndex(protoFileName, "/")+1:], ".proto")

		// Build output path matching go_package structure
		goPathParts := strings.Split(goPackageFull, "/")
		coreIdx := -1
		for i, p := range goPathParts {
			if p == "coreapi" {
				coreIdx = i
				break
			}
		}
		var outDir string
		if coreIdx >= 0 {
			outDir = strings.Join(goPathParts[coreIdx:], "/")
		} else {
			outDir = goPackage
		}

		outPath := fmt.Sprintf("%s/%s_enum_canonical.go", outDir, baseName)

		content, err := generateGoFile(protoFile, enums, goPackage)
		if err != nil {
			return err
		}

		resp.File = append(resp.File, &plugin.CodeGeneratorResponse_File{
			Name:    proto.String(outPath),
			Content: proto.String(content),
		})
	}

	return nil
}

func main() {
	req := &plugin.CodeGeneratorRequest{}
	resp := &plugin.CodeGeneratorResponse{}

	data, err := io.ReadAll(os.Stdin)
	if err != nil {
		logger.Fatal(err)
		return
	}

	if err := proto.Unmarshal(data, req); err != nil {
		logger.Fatal(err)
		return
	}

	if err := process(req, resp); err != nil {
		logger.Fatal(err)
		return
	}

	out, err := proto.Marshal(resp)
	if err != nil {
		logger.Fatal(err)
		return
	}

	os.Stdout.Write(out)
}
