// Code generated by protoc-gen-go-enum-openapi-names. DO NOT EDIT.

package common

// OpenAPIName returns the OpenAPI-compatible enum string for SortOrder.
// Prefix "SORT_ORDER_" is stripped from the proto enum value name.
func (x SortOrder) OpenAPIName() string {
	switch x {
	case SortOrder_SORT_ORDER_ASC:
		return "ASC"
	case SortOrder_SORT_ORDER_BOTH:
		return "BOTH"
	case SortOrder_SORT_ORDER_DESC:
		return "DESC"
	default:
		return ""
	}
}

// SortOrderOpenAPINames maps proto enum values to OpenAPI names.
var SortOrderOpenAPINames = map[SortOrder]string{
	SortOrder_SORT_ORDER_ASC: "ASC",
	SortOrder_SORT_ORDER_BOTH: "BOTH",
	SortOrder_SORT_ORDER_DESC: "DESC",
}

