// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: coreapi/service/user_chat.proto
// Protobuf Java Version: 4.35.1

package io.channel.api.proto.pub.coreapi.service;

@com.google.protobuf.Generated
public interface AggregateUserChatsResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coreapi.service.AggregateUserChatsResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Aggregated values keyed by the observed value of group_by.
   * </pre>
   *
   * <code>map&lt;string, string&gt; result = 1 [json_name = "result"];</code>
   */
  int getResultCount();
  /**
   * <pre>
   * Aggregated values keyed by the observed value of group_by.
   * </pre>
   *
   * <code>map&lt;string, string&gt; result = 1 [json_name = "result"];</code>
   */
  boolean containsResult(
      java.lang.String key);
  /**
   * Use {@link #getResultMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getResult();
  /**
   * <pre>
   * Aggregated values keyed by the observed value of group_by.
   * </pre>
   *
   * <code>map&lt;string, string&gt; result = 1 [json_name = "result"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getResultMap();
  /**
   * <pre>
   * Aggregated values keyed by the observed value of group_by.
   * </pre>
   *
   * <code>map&lt;string, string&gt; result = 1 [json_name = "result"];</code>
   */
  /* nullable */
java.lang.String getResultOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * Aggregated values keyed by the observed value of group_by.
   * </pre>
   *
   * <code>map&lt;string, string&gt; result = 1 [json_name = "result"];</code>
   */
  java.lang.String getResultOrThrow(
      java.lang.String key);
}
