// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: coreapi/service/announcement.proto
// Protobuf Java Version: 4.35.1

package io.channel.api.proto.pub.coreapi.service;

@com.google.protobuf.Generated
public interface AnnounceResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coreapi.service.AnnounceResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Number of managers the announcement was sent to.
   * </pre>
   *
   * <code>int32 sent = 1 [json_name = "sent"];</code>
   * @return The sent.
   */
  int getSent();
}
