// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: coreapi/service/group.proto
// Protobuf Java Version: 4.35.1

package io.channel.api.proto.pub.coreapi.service;

/**
 * <pre>
 * Creates a message in a group thread.
 *
 * Returns 404 if the thread does not exist.
 * </pre>
 *
 * Protobuf type {@code coreapi.service.CreateGroupThreadMessageRequest}
 */
@com.google.protobuf.Generated
public final class CreateGroupThreadMessageRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:coreapi.service.CreateGroupThreadMessageRequest)
    CreateGroupThreadMessageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "CreateGroupThreadMessageRequest");
  }
  // Use CreateGroupThreadMessageRequest.newBuilder() to construct.
  private CreateGroupThreadMessageRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateGroupThreadMessageRequest() {
    channelId_ = "";
    groupId_ = "";
    messageId_ = "";
    botName_ = "";
    requestId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.channel.api.proto.pub.coreapi.service.Group.internal_static_coreapi_service_CreateGroupThreadMessageRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return io.channel.api.proto.pub.coreapi.service.Group.internal_static_coreapi_service_CreateGroupThreadMessageRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.channel.api.proto.pub.coreapi.service.Group.internal_static_coreapi_service_CreateGroupThreadMessageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest.class, io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest.Builder.class);
  }

  private int bitField0_;
  public static final int CHANNEL_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object channelId_ = "";
  /**
   * <pre>
   * Channel ID the group belongs to.
   * </pre>
   *
   * <code>string channel_id = 1 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The channelId.
   */
  @java.lang.Override
  public java.lang.String getChannelId() {
    java.lang.Object ref = channelId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      channelId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Channel ID the group belongs to.
   * </pre>
   *
   * <code>string channel_id = 1 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for channelId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChannelIdBytes() {
    java.lang.Object ref = channelId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      channelId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUP_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object groupId_ = "";
  /**
   * <pre>
   * Group ID containing the thread.
   * </pre>
   *
   * <code>string group_id = 2 [json_name = "groupId", (.buf.validate.field) = { ... }</code>
   * @return The groupId.
   */
  @java.lang.Override
  public java.lang.String getGroupId() {
    java.lang.Object ref = groupId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      groupId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Group ID containing the thread.
   * </pre>
   *
   * <code>string group_id = 2 [json_name = "groupId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for groupId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupIdBytes() {
    java.lang.Object ref = groupId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groupId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object messageId_ = "";
  /**
   * <pre>
   * Root message ID of the thread.
   * </pre>
   *
   * <code>string message_id = 3 [json_name = "messageId", (.buf.validate.field) = { ... }</code>
   * @return The messageId.
   */
  @java.lang.Override
  public java.lang.String getMessageId() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Root message ID of the thread.
   * </pre>
   *
   * <code>string message_id = 3 [json_name = "messageId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for messageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageIdBytes() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 4;
  private io.channel.api.proto.pub.coreapi.model.MessageContent content_;
  /**
   * <pre>
   * Message content to send.
   * </pre>
   *
   * <code>.coreapi.model.MessageContent content = 4 [json_name = "content", (.buf.validate.field) = { ... }</code>
   * @return Whether the content field is set.
   */
  @java.lang.Override
  public boolean hasContent() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Message content to send.
   * </pre>
   *
   * <code>.coreapi.model.MessageContent content = 4 [json_name = "content", (.buf.validate.field) = { ... }</code>
   * @return The content.
   */
  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.MessageContent getContent() {
    return content_ == null ? io.channel.api.proto.pub.coreapi.model.MessageContent.getDefaultInstance() : content_;
  }
  /**
   * <pre>
   * Message content to send.
   * </pre>
   *
   * <code>.coreapi.model.MessageContent content = 4 [json_name = "content", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.MessageContentOrBuilder getContentOrBuilder() {
    return content_ == null ? io.channel.api.proto.pub.coreapi.model.MessageContent.getDefaultInstance() : content_;
  }

  public static final int BOT_NAME_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object botName_ = "";
  /**
   * <pre>
   * Bot name to use as the message author.
   *
   * +kubebuilder:validation:Nullable
   * +kubebuilder:validation:MaxLength=30
   * +kubebuilder:validation:Pattern="^[^&#64;#$%:/]+$"
   * </pre>
   *
   * <code>string bot_name = 5 [json_name = "botName", (.buf.validate.field) = { ... }</code>
   * @return The botName.
   */
  @java.lang.Override
  public java.lang.String getBotName() {
    java.lang.Object ref = botName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      botName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Bot name to use as the message author.
   *
   * +kubebuilder:validation:Nullable
   * +kubebuilder:validation:MaxLength=30
   * +kubebuilder:validation:Pattern="^[^&#64;#$%:/]+$"
   * </pre>
   *
   * <code>string bot_name = 5 [json_name = "botName", (.buf.validate.field) = { ... }</code>
   * @return The bytes for botName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBotNameBytes() {
    java.lang.Object ref = botName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      botName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BROADCAST_FIELD_NUMBER = 6;
  private boolean broadcast_ = false;
  /**
   * <pre>
   * Whether to also post this message to the main chat stream.
   *
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>bool broadcast = 6 [json_name = "broadcast"];</code>
   * @return The broadcast.
   */
  @java.lang.Override
  public boolean getBroadcast() {
    return broadcast_;
  }

  public static final int REQUEST_ID_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object requestId_ = "";
  /**
   * <pre>
   * Client-generated request identifier for idempotency.
   *
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string request_id = 7 [json_name = "requestId"];</code>
   * @return The requestId.
   */
  @java.lang.Override
  public java.lang.String getRequestId() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Client-generated request identifier for idempotency.
   *
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string request_id = 7 [json_name = "requestId"];</code>
   * @return The bytes for requestId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(channelId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, channelId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, groupId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, messageId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getContent());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(botName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, botName_);
    }
    if (broadcast_ != false) {
      output.writeBool(6, broadcast_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, requestId_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(channelId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, channelId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, groupId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, messageId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getContent());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(botName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, botName_);
    }
    if (broadcast_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, broadcast_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, requestId_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest)) {
      return super.equals(obj);
    }
    io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest other = (io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest) obj;

    if (!getChannelId()
        .equals(other.getChannelId())) return false;
    if (!getGroupId()
        .equals(other.getGroupId())) return false;
    if (!getMessageId()
        .equals(other.getMessageId())) return false;
    if (hasContent() != other.hasContent()) return false;
    if (hasContent()) {
      if (!getContent()
          .equals(other.getContent())) return false;
    }
    if (!getBotName()
        .equals(other.getBotName())) return false;
    if (getBroadcast()
        != other.getBroadcast()) return false;
    if (!getRequestId()
        .equals(other.getRequestId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHANNEL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getChannelId().hashCode();
    hash = (37 * hash) + GROUP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getGroupId().hashCode();
    hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMessageId().hashCode();
    if (hasContent()) {
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
    }
    hash = (37 * hash) + BOT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getBotName().hashCode();
    hash = (37 * hash) + BROADCAST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBroadcast());
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Creates a message in a group thread.
   *
   * Returns 404 if the thread does not exist.
   * </pre>
   *
   * Protobuf type {@code coreapi.service.CreateGroupThreadMessageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coreapi.service.CreateGroupThreadMessageRequest)
      io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.channel.api.proto.pub.coreapi.service.Group.internal_static_coreapi_service_CreateGroupThreadMessageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.channel.api.proto.pub.coreapi.service.Group.internal_static_coreapi_service_CreateGroupThreadMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest.class, io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest.Builder.class);
    }

    // Construct using io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetContentFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      channelId_ = "";
      groupId_ = "";
      messageId_ = "";
      content_ = null;
      if (contentBuilder_ != null) {
        contentBuilder_.dispose();
        contentBuilder_ = null;
      }
      botName_ = "";
      broadcast_ = false;
      requestId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.channel.api.proto.pub.coreapi.service.Group.internal_static_coreapi_service_CreateGroupThreadMessageRequest_descriptor;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest getDefaultInstanceForType() {
      return io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest build() {
      io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest buildPartial() {
      io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest result = new io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.channelId_ = channelId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.groupId_ = groupId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.messageId_ = messageId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.content_ = contentBuilder_ == null
            ? content_
            : contentBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.botName_ = botName_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.broadcast_ = broadcast_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.requestId_ = requestId_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest) {
        return mergeFrom((io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest other) {
      if (other == io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest.getDefaultInstance()) return this;
      if (!other.getChannelId().isEmpty()) {
        channelId_ = other.channelId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getGroupId().isEmpty()) {
        groupId_ = other.groupId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getMessageId().isEmpty()) {
        messageId_ = other.messageId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasContent()) {
        mergeContent(other.getContent());
      }
      if (!other.getBotName().isEmpty()) {
        botName_ = other.botName_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getBroadcast() != false) {
        setBroadcast(other.getBroadcast());
      }
      if (!other.getRequestId().isEmpty()) {
        requestId_ = other.requestId_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              channelId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              groupId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              messageId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetContentFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              botName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              broadcast_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              requestId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object channelId_ = "";
    /**
     * <pre>
     * Channel ID the group belongs to.
     * </pre>
     *
     * <code>string channel_id = 1 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @return The channelId.
     */
    public java.lang.String getChannelId() {
      java.lang.Object ref = channelId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channelId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Channel ID the group belongs to.
     * </pre>
     *
     * <code>string channel_id = 1 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @return The bytes for channelId.
     */
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      java.lang.Object ref = channelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Channel ID the group belongs to.
     * </pre>
     *
     * <code>string channel_id = 1 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @param value The channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      channelId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Channel ID the group belongs to.
     * </pre>
     *
     * <code>string channel_id = 1 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearChannelId() {
      channelId_ = getDefaultInstance().getChannelId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Channel ID the group belongs to.
     * </pre>
     *
     * <code>string channel_id = 1 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      channelId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object groupId_ = "";
    /**
     * <pre>
     * Group ID containing the thread.
     * </pre>
     *
     * <code>string group_id = 2 [json_name = "groupId", (.buf.validate.field) = { ... }</code>
     * @return The groupId.
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Group ID containing the thread.
     * </pre>
     *
     * <code>string group_id = 2 [json_name = "groupId", (.buf.validate.field) = { ... }</code>
     * @return The bytes for groupId.
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Group ID containing the thread.
     * </pre>
     *
     * <code>string group_id = 2 [json_name = "groupId", (.buf.validate.field) = { ... }</code>
     * @param value The groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      groupId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Group ID containing the thread.
     * </pre>
     *
     * <code>string group_id = 2 [json_name = "groupId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupId() {
      groupId_ = getDefaultInstance().getGroupId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Group ID containing the thread.
     * </pre>
     *
     * <code>string group_id = 2 [json_name = "groupId", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      groupId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object messageId_ = "";
    /**
     * <pre>
     * Root message ID of the thread.
     * </pre>
     *
     * <code>string message_id = 3 [json_name = "messageId", (.buf.validate.field) = { ... }</code>
     * @return The messageId.
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Root message ID of the thread.
     * </pre>
     *
     * <code>string message_id = 3 [json_name = "messageId", (.buf.validate.field) = { ... }</code>
     * @return The bytes for messageId.
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Root message ID of the thread.
     * </pre>
     *
     * <code>string message_id = 3 [json_name = "messageId", (.buf.validate.field) = { ... }</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      messageId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Root message ID of the thread.
     * </pre>
     *
     * <code>string message_id = 3 [json_name = "messageId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      messageId_ = getDefaultInstance().getMessageId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Root message ID of the thread.
     * </pre>
     *
     * <code>string message_id = 3 [json_name = "messageId", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      messageId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private io.channel.api.proto.pub.coreapi.model.MessageContent content_;
    private com.google.protobuf.SingleFieldBuilder<
        io.channel.api.proto.pub.coreapi.model.MessageContent, io.channel.api.proto.pub.coreapi.model.MessageContent.Builder, io.channel.api.proto.pub.coreapi.model.MessageContentOrBuilder> contentBuilder_;
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 4 [json_name = "content", (.buf.validate.field) = { ... }</code>
     * @return Whether the content field is set.
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 4 [json_name = "content", (.buf.validate.field) = { ... }</code>
     * @return The content.
     */
    public io.channel.api.proto.pub.coreapi.model.MessageContent getContent() {
      if (contentBuilder_ == null) {
        return content_ == null ? io.channel.api.proto.pub.coreapi.model.MessageContent.getDefaultInstance() : content_;
      } else {
        return contentBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 4 [json_name = "content", (.buf.validate.field) = { ... }</code>
     */
    public Builder setContent(io.channel.api.proto.pub.coreapi.model.MessageContent value) {
      if (contentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
      } else {
        contentBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 4 [json_name = "content", (.buf.validate.field) = { ... }</code>
     */
    public Builder setContent(
        io.channel.api.proto.pub.coreapi.model.MessageContent.Builder builderForValue) {
      if (contentBuilder_ == null) {
        content_ = builderForValue.build();
      } else {
        contentBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 4 [json_name = "content", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeContent(io.channel.api.proto.pub.coreapi.model.MessageContent value) {
      if (contentBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          content_ != null &&
          content_ != io.channel.api.proto.pub.coreapi.model.MessageContent.getDefaultInstance()) {
          getContentBuilder().mergeFrom(value);
        } else {
          content_ = value;
        }
      } else {
        contentBuilder_.mergeFrom(value);
      }
      if (content_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 4 [json_name = "content", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearContent() {
      bitField0_ = (bitField0_ & ~0x00000008);
      content_ = null;
      if (contentBuilder_ != null) {
        contentBuilder_.dispose();
        contentBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 4 [json_name = "content", (.buf.validate.field) = { ... }</code>
     */
    public io.channel.api.proto.pub.coreapi.model.MessageContent.Builder getContentBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetContentFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 4 [json_name = "content", (.buf.validate.field) = { ... }</code>
     */
    public io.channel.api.proto.pub.coreapi.model.MessageContentOrBuilder getContentOrBuilder() {
      if (contentBuilder_ != null) {
        return contentBuilder_.getMessageOrBuilder();
      } else {
        return content_ == null ?
            io.channel.api.proto.pub.coreapi.model.MessageContent.getDefaultInstance() : content_;
      }
    }
    /**
     * <pre>
     * Message content to send.
     * </pre>
     *
     * <code>.coreapi.model.MessageContent content = 4 [json_name = "content", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.channel.api.proto.pub.coreapi.model.MessageContent, io.channel.api.proto.pub.coreapi.model.MessageContent.Builder, io.channel.api.proto.pub.coreapi.model.MessageContentOrBuilder> 
        internalGetContentFieldBuilder() {
      if (contentBuilder_ == null) {
        contentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.channel.api.proto.pub.coreapi.model.MessageContent, io.channel.api.proto.pub.coreapi.model.MessageContent.Builder, io.channel.api.proto.pub.coreapi.model.MessageContentOrBuilder>(
                getContent(),
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      return contentBuilder_;
    }

    private java.lang.Object botName_ = "";
    /**
     * <pre>
     * Bot name to use as the message author.
     *
     * +kubebuilder:validation:Nullable
     * +kubebuilder:validation:MaxLength=30
     * +kubebuilder:validation:Pattern="^[^&#64;#$%:/]+$"
     * </pre>
     *
     * <code>string bot_name = 5 [json_name = "botName", (.buf.validate.field) = { ... }</code>
     * @return The botName.
     */
    public java.lang.String getBotName() {
      java.lang.Object ref = botName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        botName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Bot name to use as the message author.
     *
     * +kubebuilder:validation:Nullable
     * +kubebuilder:validation:MaxLength=30
     * +kubebuilder:validation:Pattern="^[^&#64;#$%:/]+$"
     * </pre>
     *
     * <code>string bot_name = 5 [json_name = "botName", (.buf.validate.field) = { ... }</code>
     * @return The bytes for botName.
     */
    public com.google.protobuf.ByteString
        getBotNameBytes() {
      java.lang.Object ref = botName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        botName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Bot name to use as the message author.
     *
     * +kubebuilder:validation:Nullable
     * +kubebuilder:validation:MaxLength=30
     * +kubebuilder:validation:Pattern="^[^&#64;#$%:/]+$"
     * </pre>
     *
     * <code>string bot_name = 5 [json_name = "botName", (.buf.validate.field) = { ... }</code>
     * @param value The botName to set.
     * @return This builder for chaining.
     */
    public Builder setBotName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      botName_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Bot name to use as the message author.
     *
     * +kubebuilder:validation:Nullable
     * +kubebuilder:validation:MaxLength=30
     * +kubebuilder:validation:Pattern="^[^&#64;#$%:/]+$"
     * </pre>
     *
     * <code>string bot_name = 5 [json_name = "botName", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearBotName() {
      botName_ = getDefaultInstance().getBotName();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Bot name to use as the message author.
     *
     * +kubebuilder:validation:Nullable
     * +kubebuilder:validation:MaxLength=30
     * +kubebuilder:validation:Pattern="^[^&#64;#$%:/]+$"
     * </pre>
     *
     * <code>string bot_name = 5 [json_name = "botName", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for botName to set.
     * @return This builder for chaining.
     */
    public Builder setBotNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      botName_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private boolean broadcast_ ;
    /**
     * <pre>
     * Whether to also post this message to the main chat stream.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>bool broadcast = 6 [json_name = "broadcast"];</code>
     * @return The broadcast.
     */
    @java.lang.Override
    public boolean getBroadcast() {
      return broadcast_;
    }
    /**
     * <pre>
     * Whether to also post this message to the main chat stream.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>bool broadcast = 6 [json_name = "broadcast"];</code>
     * @param value The broadcast to set.
     * @return This builder for chaining.
     */
    public Builder setBroadcast(boolean value) {

      broadcast_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether to also post this message to the main chat stream.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>bool broadcast = 6 [json_name = "broadcast"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBroadcast() {
      bitField0_ = (bitField0_ & ~0x00000020);
      broadcast_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object requestId_ = "";
    /**
     * <pre>
     * Client-generated request identifier for idempotency.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string request_id = 7 [json_name = "requestId"];</code>
     * @return The requestId.
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Client-generated request identifier for idempotency.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string request_id = 7 [json_name = "requestId"];</code>
     * @return The bytes for requestId.
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Client-generated request identifier for idempotency.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string request_id = 7 [json_name = "requestId"];</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      requestId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Client-generated request identifier for idempotency.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string request_id = 7 [json_name = "requestId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      requestId_ = getDefaultInstance().getRequestId();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Client-generated request identifier for idempotency.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string request_id = 7 [json_name = "requestId"];</code>
     * @param value The bytes for requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      requestId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    /* Generated by protoc-gen-java-set-or-clear */
    
    /**
     * @param value The channel_id to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearChannelId(java.lang.String value) {
    	if (value == null)
    		return clearChannelId();
    	else
    		return setChannelId(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearChannelId(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearChannelId();
    	else
    		return setChannelId(mapFunc.apply(value));
    }
    	
    /**
     * @param value The group_id to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearGroupId(java.lang.String value) {
    	if (value == null)
    		return clearGroupId();
    	else
    		return setGroupId(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearGroupId(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearGroupId();
    	else
    		return setGroupId(mapFunc.apply(value));
    }
    	
    /**
     * @param value The message_id to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearMessageId(java.lang.String value) {
    	if (value == null)
    		return clearMessageId();
    	else
    		return setMessageId(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearMessageId(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearMessageId();
    	else
    		return setMessageId(mapFunc.apply(value));
    }
    	
    /**
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearContent(io.channel.api.proto.pub.coreapi.model.MessageContent value) {
    	if (value == null)
    		return clearContent();
    	else
    		return setContent(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearContent(T value, java.util.function.Function<T, io.channel.api.proto.pub.coreapi.model.MessageContent> mapFunc) {
    	if (value == null)
    		return clearContent();
    	else
    		return setContent(mapFunc.apply(value));
    }
    	
    /**
     * @param value The bot_name to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearBotName(java.lang.String value) {
    	if (value == null)
    		return clearBotName();
    	else
    		return setBotName(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearBotName(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearBotName();
    	else
    		return setBotName(mapFunc.apply(value));
    }
    	
    /**
     * @param value The broadcast to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearBroadcast(java.lang.Boolean value) {
    	if (value == null)
    		return clearBroadcast();
    	else
    		return setBroadcast(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearBroadcast(T value, java.util.function.Function<T, java.lang.Boolean> mapFunc) {
    	if (value == null)
    		return clearBroadcast();
    	else
    		return setBroadcast(mapFunc.apply(value));
    }
    	
    /**
     * @param value The request_id to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearRequestId(java.lang.String value) {
    	if (value == null)
    		return clearRequestId();
    	else
    		return setRequestId(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearRequestId(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearRequestId();
    	else
    		return setRequestId(mapFunc.apply(value));
    }
    	
    // @@protoc_insertion_point(builder_scope:coreapi.service.CreateGroupThreadMessageRequest)
  }

  // @@protoc_insertion_point(class_scope:coreapi.service.CreateGroupThreadMessageRequest)
  private static final io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest();
  }

  public static io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateGroupThreadMessageRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateGroupThreadMessageRequest>() {
    @java.lang.Override
    public CreateGroupThreadMessageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateGroupThreadMessageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateGroupThreadMessageRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.service.CreateGroupThreadMessageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
