// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: coreapi/service/event.proto
// Protobuf Java Version: 4.35.1

package io.channel.api.proto.pub.coreapi.service;

@com.google.protobuf.Generated
public interface DeleteEventResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coreapi.service.DeleteEventResult)
    com.google.protobuf.MessageOrBuilder {
}
