// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/service/chat_bookmark.proto

package io.channel.api.proto.pub.coreapi.service;

public interface GetChatBookmarkResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coreapi.service.GetChatBookmarkResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.coreapi.model.ChatBookmark chat_bookmark = 1 [json_name = "chatBookmark"];</code>
   * @return Whether the chatBookmark field is set.
   */
  boolean hasChatBookmark();
  /**
   * <code>.coreapi.model.ChatBookmark chat_bookmark = 1 [json_name = "chatBookmark"];</code>
   * @return The chatBookmark.
   */
  io.channel.api.proto.pub.coreapi.model.ChatBookmark getChatBookmark();
  /**
   * <code>.coreapi.model.ChatBookmark chat_bookmark = 1 [json_name = "chatBookmark"];</code>
   */
  io.channel.api.proto.pub.coreapi.model.ChatBookmarkOrBuilder getChatBookmarkOrBuilder();
}
