// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: coreapi/service/webhook.proto
// Protobuf Java Version: 4.35.1

package io.channel.api.proto.pub.coreapi.service;

/**
 * <pre>
 * Updates a webhook partially.
 * Only specified fields are modified; omitted fields remain unchanged.
 * </pre>
 *
 * Protobuf type {@code coreapi.service.PatchWebhookRequest}
 */
@com.google.protobuf.Generated
public final class PatchWebhookRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:coreapi.service.PatchWebhookRequest)
    PatchWebhookRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "PatchWebhookRequest");
  }
  // Use PatchWebhookRequest.newBuilder() to construct.
  private PatchWebhookRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PatchWebhookRequest() {
    webhookId_ = "";
    channelId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.channel.api.proto.pub.coreapi.service.Webhook.internal_static_coreapi_service_PatchWebhookRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return io.channel.api.proto.pub.coreapi.service.Webhook.internal_static_coreapi_service_PatchWebhookRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.channel.api.proto.pub.coreapi.service.Webhook.internal_static_coreapi_service_PatchWebhookRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.class, io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.Builder.class);
  }

  public interface PatchWebhookBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:coreapi.service.PatchWebhookRequest.PatchWebhookBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Webhook display name. Must be unique within the channel.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * Webhook display name. Must be unique within the channel.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * Destination URL that receives webhook payloads.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string url = 2 [json_name = "url"];</code>
     * @return The url.
     */
    java.lang.String getUrl();
    /**
     * <pre>
     * Destination URL that receives webhook payloads.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string url = 2 [json_name = "url"];</code>
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <pre>
     * Event scopes that trigger this webhook.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
     * @return A list containing the scopes.
     */
    java.util.List<io.channel.api.proto.pub.coreapi.model.WebhookScope> getScopesList();
    /**
     * <pre>
     * Event scopes that trigger this webhook.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
     * @return The count of scopes.
     */
    int getScopesCount();
    /**
     * <pre>
     * Event scopes that trigger this webhook.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
     * @param index The index of the element to return.
     * @return The scopes at the given index.
     */
    io.channel.api.proto.pub.coreapi.model.WebhookScope getScopes(int index);
    /**
     * <pre>
     * Event scopes that trigger this webhook.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
     * @return A list containing the enum numeric values on the wire for scopes.
     */
    java.util.List<java.lang.Integer>
    getScopesValueList();
    /**
     * <pre>
     * Event scopes that trigger this webhook.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of scopes at the given index.
     */
    int getScopesValue(int index);

    /**
     * <pre>
     * API version for webhook payloads.
     *
     * +kubebuilder:validation:Nullable
     * +kubebuilder:validation:Enum={"v4","v5"}
     * </pre>
     *
     * <code>string api_version = 4 [json_name = "apiVersion"];</code>
     * @return The apiVersion.
     */
    java.lang.String getApiVersion();
    /**
     * <pre>
     * API version for webhook payloads.
     *
     * +kubebuilder:validation:Nullable
     * +kubebuilder:validation:Enum={"v4","v5"}
     * </pre>
     *
     * <code>string api_version = 4 [json_name = "apiVersion"];</code>
     * @return The bytes for apiVersion.
     */
    com.google.protobuf.ByteString
        getApiVersionBytes();
  }
  /**
   * Protobuf type {@code coreapi.service.PatchWebhookRequest.PatchWebhookBody}
   */
  public static final class PatchWebhookBody extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:coreapi.service.PatchWebhookRequest.PatchWebhookBody)
      PatchWebhookBodyOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "PatchWebhookBody");
    }
    // Use PatchWebhookBody.newBuilder() to construct.
    private PatchWebhookBody(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PatchWebhookBody() {
      name_ = "";
      url_ = "";
      scopes_ = emptyIntList();
      apiVersion_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.channel.api.proto.pub.coreapi.service.Webhook.internal_static_coreapi_service_PatchWebhookRequest_PatchWebhookBody_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return io.channel.api.proto.pub.coreapi.service.Webhook.internal_static_coreapi_service_PatchWebhookRequest_PatchWebhookBody_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.channel.api.proto.pub.coreapi.service.Webhook.internal_static_coreapi_service_PatchWebhookRequest_PatchWebhookBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody.class, io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <pre>
     * Webhook display name. Must be unique within the channel.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Webhook display name. Must be unique within the channel.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URL_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object url_ = "";
    /**
     * <pre>
     * Destination URL that receives webhook payloads.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string url = 2 [json_name = "url"];</code>
     * @return The url.
     */
    @java.lang.Override
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Destination URL that receives webhook payloads.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>string url = 2 [json_name = "url"];</code>
     * @return The bytes for url.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCOPES_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList scopes_ =
        emptyIntList();
    private static final     com.google.protobuf.Internal.IntListAdapter.IntConverter<
        io.channel.api.proto.pub.coreapi.model.WebhookScope> scopes_converter_ =
            new com.google.protobuf.Internal.IntListAdapter.IntConverter<
                io.channel.api.proto.pub.coreapi.model.WebhookScope>() {
              public io.channel.api.proto.pub.coreapi.model.WebhookScope convert(int from) {
                io.channel.api.proto.pub.coreapi.model.WebhookScope result = io.channel.api.proto.pub.coreapi.model.WebhookScope.forNumber(from);
                return result == null ? io.channel.api.proto.pub.coreapi.model.WebhookScope.UNRECOGNIZED : result;
              }
            };
    /**
     * <pre>
     * Event scopes that trigger this webhook.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
     * @return A list containing the scopes.
     */
    @java.lang.Override
    public java.util.List<io.channel.api.proto.pub.coreapi.model.WebhookScope> getScopesList() {
      return new com.google.protobuf.Internal.IntListAdapter<
          io.channel.api.proto.pub.coreapi.model.WebhookScope>(scopes_, scopes_converter_);
    }
    /**
     * <pre>
     * Event scopes that trigger this webhook.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
     * @return The count of scopes.
     */
    @java.lang.Override
    public int getScopesCount() {
      return scopes_.size();
    }
    /**
     * <pre>
     * Event scopes that trigger this webhook.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
     * @param index The index of the element to return.
     * @return The scopes at the given index.
     */
    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.WebhookScope getScopes(int index) {
      return scopes_converter_.convert(scopes_.getInt(index));
    }
    /**
     * <pre>
     * Event scopes that trigger this webhook.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
     * @return A list containing the enum numeric values on the wire for scopes.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
    getScopesValueList() {
      return scopes_;
    }
    /**
     * <pre>
     * Event scopes that trigger this webhook.
     *
     * +kubebuilder:validation:Nullable
     * </pre>
     *
     * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of scopes at the given index.
     */
    @java.lang.Override
    public int getScopesValue(int index) {
      return scopes_.getInt(index);
    }
    private int scopesMemoizedSerializedSize;

    public static final int API_VERSION_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object apiVersion_ = "";
    /**
     * <pre>
     * API version for webhook payloads.
     *
     * +kubebuilder:validation:Nullable
     * +kubebuilder:validation:Enum={"v4","v5"}
     * </pre>
     *
     * <code>string api_version = 4 [json_name = "apiVersion"];</code>
     * @return The apiVersion.
     */
    @java.lang.Override
    public java.lang.String getApiVersion() {
      java.lang.Object ref = apiVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apiVersion_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * API version for webhook payloads.
     *
     * +kubebuilder:validation:Nullable
     * +kubebuilder:validation:Enum={"v4","v5"}
     * </pre>
     *
     * <code>string api_version = 4 [json_name = "apiVersion"];</code>
     * @return The bytes for apiVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getApiVersionBytes() {
      java.lang.Object ref = apiVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apiVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(url_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, url_);
      }
      if (getScopesList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(scopesMemoizedSerializedSize);
      }
      for (int i = 0; i < scopes_.size(); i++) {
        output.writeEnumNoTag(scopes_.getInt(i));
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(apiVersion_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, apiVersion_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(url_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, url_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < scopes_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(scopes_.getInt(i));
        }
        size += dataSize;
        if (!getScopesList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataSize);
        }scopesMemoizedSerializedSize = dataSize;
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(apiVersion_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, apiVersion_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody)) {
        return super.equals(obj);
      }
      io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody other = (io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getUrl()
          .equals(other.getUrl())) return false;
      if (!scopes_.equals(other.scopes_)) return false;
      if (!getApiVersion()
          .equals(other.getApiVersion())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      if (getScopesCount() > 0) {
        hash = (37 * hash) + SCOPES_FIELD_NUMBER;
        hash = (53 * hash) + scopes_.hashCode();
      }
      hash = (37 * hash) + API_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getApiVersion().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code coreapi.service.PatchWebhookRequest.PatchWebhookBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:coreapi.service.PatchWebhookRequest.PatchWebhookBody)
        io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.channel.api.proto.pub.coreapi.service.Webhook.internal_static_coreapi_service_PatchWebhookRequest_PatchWebhookBody_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.channel.api.proto.pub.coreapi.service.Webhook.internal_static_coreapi_service_PatchWebhookRequest_PatchWebhookBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody.class, io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody.Builder.class);
      }

      // Construct using io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        url_ = "";
        scopes_ = emptyIntList();
        apiVersion_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.channel.api.proto.pub.coreapi.service.Webhook.internal_static_coreapi_service_PatchWebhookRequest_PatchWebhookBody_descriptor;
      }

      @java.lang.Override
      public io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody getDefaultInstanceForType() {
        return io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody.getDefaultInstance();
      }

      @java.lang.Override
      public io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody build() {
        io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody buildPartial() {
        io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody result = new io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.url_ = url_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          scopes_.makeImmutable();
          result.scopes_ = scopes_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.apiVersion_ = apiVersion_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody) {
          return mergeFrom((io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody other) {
        if (other == io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.scopes_.isEmpty()) {
          if (scopes_.isEmpty()) {
            scopes_ = other.scopes_;
            scopes_.makeImmutable();
            bitField0_ |= 0x00000004;
          } else {
            ensureScopesIsMutable();
            scopes_.addAll(other.scopes_);
          }
          onChanged();
        }
        if (!other.getApiVersion().isEmpty()) {
          apiVersion_ = other.apiVersion_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                url_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                int tmpRaw = input.readEnum();
                ensureScopesIsMutable();
                scopes_.addInt(tmpRaw);
                break;
              } // case 24
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureScopesIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  scopes_.addInt(input.readEnum());
                }
                input.popLimit(limit);
                break;
              } // case 26
              case 34: {
                apiVersion_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * Webhook display name. Must be unique within the channel.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>string name = 1 [json_name = "name"];</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Webhook display name. Must be unique within the channel.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>string name = 1 [json_name = "name"];</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Webhook display name. Must be unique within the channel.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>string name = 1 [json_name = "name"];</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Webhook display name. Must be unique within the channel.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>string name = 1 [json_name = "name"];</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Webhook display name. Must be unique within the channel.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>string name = 1 [json_name = "name"];</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <pre>
       * Destination URL that receives webhook payloads.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>string url = 2 [json_name = "url"];</code>
       * @return The url.
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Destination URL that receives webhook payloads.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>string url = 2 [json_name = "url"];</code>
       * @return The bytes for url.
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Destination URL that receives webhook payloads.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>string url = 2 [json_name = "url"];</code>
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        url_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Destination URL that receives webhook payloads.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>string url = 2 [json_name = "url"];</code>
       * @return This builder for chaining.
       */
      public Builder clearUrl() {
        url_ = getDefaultInstance().getUrl();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Destination URL that receives webhook payloads.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>string url = 2 [json_name = "url"];</code>
       * @param value The bytes for url to set.
       * @return This builder for chaining.
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        url_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList scopes_ = emptyIntList();
      private void ensureScopesIsMutable() {
        if (!scopes_.isModifiable()) {
          scopes_ = makeMutableCopy(scopes_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <pre>
       * Event scopes that trigger this webhook.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
       * @return A list containing the scopes.
       */
      public java.util.List<io.channel.api.proto.pub.coreapi.model.WebhookScope> getScopesList() {
        return new com.google.protobuf.Internal.IntListAdapter<
            io.channel.api.proto.pub.coreapi.model.WebhookScope>(scopes_, scopes_converter_);
      }
      /**
       * <pre>
       * Event scopes that trigger this webhook.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
       * @return The count of scopes.
       */
      public int getScopesCount() {
        return scopes_.size();
      }
      /**
       * <pre>
       * Event scopes that trigger this webhook.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
       * @param index The index of the element to return.
       * @return The scopes at the given index.
       */
      public io.channel.api.proto.pub.coreapi.model.WebhookScope getScopes(int index) {
        return scopes_converter_.convert(scopes_.getInt(index));
      }
      /**
       * <pre>
       * Event scopes that trigger this webhook.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
       * @param index The index to set the value at.
       * @param value The scopes to set.
       * @throws IllegalArgumentException if UNRECOGNIZED is provided.
       * @return This builder for chaining.
       */
      public Builder setScopes(
          int index, io.channel.api.proto.pub.coreapi.model.WebhookScope value) {
        if (value == null) { throw new NullPointerException(); }
        ensureScopesIsMutable();
        scopes_.setInt(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Event scopes that trigger this webhook.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
       * @param value The scopes to add.
       * @return This builder for chaining.
       */
      public Builder addScopes(io.channel.api.proto.pub.coreapi.model.WebhookScope value) {
        if (value == null) { throw new NullPointerException(); }
        ensureScopesIsMutable();
        scopes_.addInt(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Event scopes that trigger this webhook.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
       * @param values The scopes to add.
       * @throws IllegalArgumentException if UNRECOGNIZED is provided.
       * @return This builder for chaining.
       */
      public Builder addAllScopes(
          java.lang.Iterable<? extends io.channel.api.proto.pub.coreapi.model.WebhookScope> values) {
        ensureScopesIsMutable();
        for (io.channel.api.proto.pub.coreapi.model.WebhookScope value : values) {
          scopes_.addInt(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Event scopes that trigger this webhook.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
       * @return This builder for chaining.
       */
      public Builder clearScopes() {
        scopes_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Event scopes that trigger this webhook.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
       * @return A list containing the enum numeric values on the wire for scopes.
       */
      public java.util.List<java.lang.Integer>
      getScopesValueList() {
        scopes_.makeImmutable();
        return scopes_;
      }
      /**
       * <pre>
       * Event scopes that trigger this webhook.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
       * @param index The index of the value to return.
       * @return The enum numeric value on the wire of scopes at the given index.
       */
      public int getScopesValue(int index) {
        return scopes_.getInt(index);
      }
      /**
       * <pre>
       * Event scopes that trigger this webhook.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
       * @param index The index to set the value at.
       * @param value The enum numeric value on the wire for scopes to set.
       * @return This builder for chaining.
       */
      public Builder setScopesValue(
          int index, int value) {
        ensureScopesIsMutable();
        scopes_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Event scopes that trigger this webhook.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
       * @param value The enum numeric value on the wire for scopes to add.
       * @return This builder for chaining.
       */
      public Builder addScopesValue(int value) {
        ensureScopesIsMutable();
        scopes_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Event scopes that trigger this webhook.
       *
       * +kubebuilder:validation:Nullable
       * </pre>
       *
       * <code>repeated .coreapi.model.WebhookScope scopes = 3 [json_name = "scopes"];</code>
       * @param values The enum numeric values on the wire for scopes to add.
       * @return This builder for chaining.
       */
      public Builder addAllScopesValue(
          java.lang.Iterable<java.lang.Integer> values) {
        ensureScopesIsMutable();
        for (int value : values) {
          scopes_.addInt(value);
        }
        onChanged();
        return this;
      }

      private java.lang.Object apiVersion_ = "";
      /**
       * <pre>
       * API version for webhook payloads.
       *
       * +kubebuilder:validation:Nullable
       * +kubebuilder:validation:Enum={"v4","v5"}
       * </pre>
       *
       * <code>string api_version = 4 [json_name = "apiVersion"];</code>
       * @return The apiVersion.
       */
      public java.lang.String getApiVersion() {
        java.lang.Object ref = apiVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          apiVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * API version for webhook payloads.
       *
       * +kubebuilder:validation:Nullable
       * +kubebuilder:validation:Enum={"v4","v5"}
       * </pre>
       *
       * <code>string api_version = 4 [json_name = "apiVersion"];</code>
       * @return The bytes for apiVersion.
       */
      public com.google.protobuf.ByteString
          getApiVersionBytes() {
        java.lang.Object ref = apiVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          apiVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * API version for webhook payloads.
       *
       * +kubebuilder:validation:Nullable
       * +kubebuilder:validation:Enum={"v4","v5"}
       * </pre>
       *
       * <code>string api_version = 4 [json_name = "apiVersion"];</code>
       * @param value The apiVersion to set.
       * @return This builder for chaining.
       */
      public Builder setApiVersion(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        apiVersion_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * API version for webhook payloads.
       *
       * +kubebuilder:validation:Nullable
       * +kubebuilder:validation:Enum={"v4","v5"}
       * </pre>
       *
       * <code>string api_version = 4 [json_name = "apiVersion"];</code>
       * @return This builder for chaining.
       */
      public Builder clearApiVersion() {
        apiVersion_ = getDefaultInstance().getApiVersion();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * API version for webhook payloads.
       *
       * +kubebuilder:validation:Nullable
       * +kubebuilder:validation:Enum={"v4","v5"}
       * </pre>
       *
       * <code>string api_version = 4 [json_name = "apiVersion"];</code>
       * @param value The bytes for apiVersion to set.
       * @return This builder for chaining.
       */
      public Builder setApiVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        apiVersion_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      /* Generated by protoc-gen-java-set-or-clear */
      
      /**
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setOrClearName(java.lang.String value) {
      	if (value == null)
      		return clearName();
      	else
      		return setName(value);
      }
      	
      /**
       * @param value The value to map.
       * @param mapFunc The function to map the value into the proto message.
       * @return This builder for chaining.
       */
      public <T> Builder mapOrClearName(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
      	if (value == null)
      		return clearName();
      	else
      		return setName(mapFunc.apply(value));
      }
      	
      /**
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setOrClearUrl(java.lang.String value) {
      	if (value == null)
      		return clearUrl();
      	else
      		return setUrl(value);
      }
      	
      /**
       * @param value The value to map.
       * @param mapFunc The function to map the value into the proto message.
       * @return This builder for chaining.
       */
      public <T> Builder mapOrClearUrl(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
      	if (value == null)
      		return clearUrl();
      	else
      		return setUrl(mapFunc.apply(value));
      }
      	
      /**
       * @param values The scopes to add.
       * @return This builder for chaining.
       */
      public Builder addAllOrClearScopes(java.lang.Iterable<? extends io.channel.api.proto.pub.coreapi.model.WebhookScope> values) {
      	if (values == null)
      		return clearScopes();
      	else
      		return addAllScopes(values);
      }
      	
      /**
       * @param values The values to map.
       * @param mapFunc The function to map the values into each proto message.
       * @return This builder for chaining.
       */
      public <T> Builder mapAllOrClearScopes(java.lang.Iterable<T> values, java.util.function.Function<T, ? extends io.channel.api.proto.pub.coreapi.model.WebhookScope> mapFunc) {
      	if (values == null)
      		return clearScopes();
      	else {
      		values.forEach(value -> addScopes(mapFunc.apply(value)));
      		return this;
      	}
      }
      	
      /**
       * @param value The api_version to set.
       * @return This builder for chaining.
       */
      public Builder setOrClearApiVersion(java.lang.String value) {
      	if (value == null)
      		return clearApiVersion();
      	else
      		return setApiVersion(value);
      }
      	
      /**
       * @param value The value to map.
       * @param mapFunc The function to map the value into the proto message.
       * @return This builder for chaining.
       */
      public <T> Builder mapOrClearApiVersion(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
      	if (value == null)
      		return clearApiVersion();
      	else
      		return setApiVersion(mapFunc.apply(value));
      }
      	
      // @@protoc_insertion_point(builder_scope:coreapi.service.PatchWebhookRequest.PatchWebhookBody)
    }

    // @@protoc_insertion_point(class_scope:coreapi.service.PatchWebhookRequest.PatchWebhookBody)
    private static final io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody();
    }

    public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PatchWebhookBody>
        PARSER = new com.google.protobuf.AbstractParser<PatchWebhookBody>() {
      @java.lang.Override
      public PatchWebhookBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PatchWebhookBody> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PatchWebhookBody> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int WEBHOOK_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object webhookId_ = "";
  /**
   * <pre>
   * Webhook ID to update.
   * </pre>
   *
   * <code>string webhook_id = 1 [json_name = "webhookId", (.buf.validate.field) = { ... }</code>
   * @return The webhookId.
   */
  @java.lang.Override
  public java.lang.String getWebhookId() {
    java.lang.Object ref = webhookId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      webhookId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Webhook ID to update.
   * </pre>
   *
   * <code>string webhook_id = 1 [json_name = "webhookId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for webhookId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWebhookIdBytes() {
    java.lang.Object ref = webhookId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      webhookId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHANNEL_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object channelId_ = "";
  /**
   * <pre>
   * Channel ID the webhook belongs to.
   * </pre>
   *
   * <code>string channel_id = 2 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The channelId.
   */
  @java.lang.Override
  public java.lang.String getChannelId() {
    java.lang.Object ref = channelId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      channelId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Channel ID the webhook belongs to.
   * </pre>
   *
   * <code>string channel_id = 2 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for channelId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChannelIdBytes() {
    java.lang.Object ref = channelId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      channelId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BODY_FIELD_NUMBER = 3;
  private io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody body_;
  /**
   * <pre>
   * Patch body. Only fields listed in update_mask are applied.
   * </pre>
   *
   * <code>.coreapi.service.PatchWebhookRequest.PatchWebhookBody body = 3 [json_name = "body", (.buf.validate.field) = { ... }</code>
   * @return Whether the body field is set.
   */
  @java.lang.Override
  public boolean hasBody() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Patch body. Only fields listed in update_mask are applied.
   * </pre>
   *
   * <code>.coreapi.service.PatchWebhookRequest.PatchWebhookBody body = 3 [json_name = "body", (.buf.validate.field) = { ... }</code>
   * @return The body.
   */
  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody getBody() {
    return body_ == null ? io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody.getDefaultInstance() : body_;
  }
  /**
   * <pre>
   * Patch body. Only fields listed in update_mask are applied.
   * </pre>
   *
   * <code>.coreapi.service.PatchWebhookRequest.PatchWebhookBody body = 3 [json_name = "body", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBodyOrBuilder getBodyOrBuilder() {
    return body_ == null ? io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody.getDefaultInstance() : body_;
  }

  public static final int UPDATE_MASK_FIELD_NUMBER = 4;
  private com.google.protobuf.FieldMask updateMask_;
  /**
   * <pre>
   * Set of field paths (relative to PatchWebhookBody) to update.
   * Unlisted fields remain unchanged.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 4 [json_name = "updateMask", (.buf.validate.field) = { ... }</code>
   * @return Whether the updateMask field is set.
   */
  @java.lang.Override
  public boolean hasUpdateMask() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Set of field paths (relative to PatchWebhookBody) to update.
   * Unlisted fields remain unchanged.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 4 [json_name = "updateMask", (.buf.validate.field) = { ... }</code>
   * @return The updateMask.
   */
  @java.lang.Override
  public com.google.protobuf.FieldMask getUpdateMask() {
    return updateMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : updateMask_;
  }
  /**
   * <pre>
   * Set of field paths (relative to PatchWebhookBody) to update.
   * Unlisted fields remain unchanged.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 4 [json_name = "updateMask", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder() {
    return updateMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : updateMask_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(webhookId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, webhookId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(channelId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, channelId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getBody());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getUpdateMask());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(webhookId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, webhookId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(channelId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, channelId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getBody());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getUpdateMask());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest)) {
      return super.equals(obj);
    }
    io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest other = (io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest) obj;

    if (!getWebhookId()
        .equals(other.getWebhookId())) return false;
    if (!getChannelId()
        .equals(other.getChannelId())) return false;
    if (hasBody() != other.hasBody()) return false;
    if (hasBody()) {
      if (!getBody()
          .equals(other.getBody())) return false;
    }
    if (hasUpdateMask() != other.hasUpdateMask()) return false;
    if (hasUpdateMask()) {
      if (!getUpdateMask()
          .equals(other.getUpdateMask())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WEBHOOK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getWebhookId().hashCode();
    hash = (37 * hash) + CHANNEL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getChannelId().hashCode();
    if (hasBody()) {
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
    }
    if (hasUpdateMask()) {
      hash = (37 * hash) + UPDATE_MASK_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateMask().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Updates a webhook partially.
   * Only specified fields are modified; omitted fields remain unchanged.
   * </pre>
   *
   * Protobuf type {@code coreapi.service.PatchWebhookRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coreapi.service.PatchWebhookRequest)
      io.channel.api.proto.pub.coreapi.service.PatchWebhookRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.channel.api.proto.pub.coreapi.service.Webhook.internal_static_coreapi_service_PatchWebhookRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.channel.api.proto.pub.coreapi.service.Webhook.internal_static_coreapi_service_PatchWebhookRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.class, io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.Builder.class);
    }

    // Construct using io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetBodyFieldBuilder();
        internalGetUpdateMaskFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      webhookId_ = "";
      channelId_ = "";
      body_ = null;
      if (bodyBuilder_ != null) {
        bodyBuilder_.dispose();
        bodyBuilder_ = null;
      }
      updateMask_ = null;
      if (updateMaskBuilder_ != null) {
        updateMaskBuilder_.dispose();
        updateMaskBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.channel.api.proto.pub.coreapi.service.Webhook.internal_static_coreapi_service_PatchWebhookRequest_descriptor;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest getDefaultInstanceForType() {
      return io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest build() {
      io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest buildPartial() {
      io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest result = new io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.webhookId_ = webhookId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.channelId_ = channelId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.body_ = bodyBuilder_ == null
            ? body_
            : bodyBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.updateMask_ = updateMaskBuilder_ == null
            ? updateMask_
            : updateMaskBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest) {
        return mergeFrom((io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest other) {
      if (other == io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.getDefaultInstance()) return this;
      if (!other.getWebhookId().isEmpty()) {
        webhookId_ = other.webhookId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getChannelId().isEmpty()) {
        channelId_ = other.channelId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasBody()) {
        mergeBody(other.getBody());
      }
      if (other.hasUpdateMask()) {
        mergeUpdateMask(other.getUpdateMask());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              webhookId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              channelId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetBodyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetUpdateMaskFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object webhookId_ = "";
    /**
     * <pre>
     * Webhook ID to update.
     * </pre>
     *
     * <code>string webhook_id = 1 [json_name = "webhookId", (.buf.validate.field) = { ... }</code>
     * @return The webhookId.
     */
    public java.lang.String getWebhookId() {
      java.lang.Object ref = webhookId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        webhookId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Webhook ID to update.
     * </pre>
     *
     * <code>string webhook_id = 1 [json_name = "webhookId", (.buf.validate.field) = { ... }</code>
     * @return The bytes for webhookId.
     */
    public com.google.protobuf.ByteString
        getWebhookIdBytes() {
      java.lang.Object ref = webhookId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        webhookId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Webhook ID to update.
     * </pre>
     *
     * <code>string webhook_id = 1 [json_name = "webhookId", (.buf.validate.field) = { ... }</code>
     * @param value The webhookId to set.
     * @return This builder for chaining.
     */
    public Builder setWebhookId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      webhookId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Webhook ID to update.
     * </pre>
     *
     * <code>string webhook_id = 1 [json_name = "webhookId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearWebhookId() {
      webhookId_ = getDefaultInstance().getWebhookId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Webhook ID to update.
     * </pre>
     *
     * <code>string webhook_id = 1 [json_name = "webhookId", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for webhookId to set.
     * @return This builder for chaining.
     */
    public Builder setWebhookIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      webhookId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object channelId_ = "";
    /**
     * <pre>
     * Channel ID the webhook belongs to.
     * </pre>
     *
     * <code>string channel_id = 2 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @return The channelId.
     */
    public java.lang.String getChannelId() {
      java.lang.Object ref = channelId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channelId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Channel ID the webhook belongs to.
     * </pre>
     *
     * <code>string channel_id = 2 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @return The bytes for channelId.
     */
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      java.lang.Object ref = channelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Channel ID the webhook belongs to.
     * </pre>
     *
     * <code>string channel_id = 2 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @param value The channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      channelId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Channel ID the webhook belongs to.
     * </pre>
     *
     * <code>string channel_id = 2 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearChannelId() {
      channelId_ = getDefaultInstance().getChannelId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Channel ID the webhook belongs to.
     * </pre>
     *
     * <code>string channel_id = 2 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      channelId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody body_;
    private com.google.protobuf.SingleFieldBuilder<
        io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody, io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody.Builder, io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBodyOrBuilder> bodyBuilder_;
    /**
     * <pre>
     * Patch body. Only fields listed in update_mask are applied.
     * </pre>
     *
     * <code>.coreapi.service.PatchWebhookRequest.PatchWebhookBody body = 3 [json_name = "body", (.buf.validate.field) = { ... }</code>
     * @return Whether the body field is set.
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Patch body. Only fields listed in update_mask are applied.
     * </pre>
     *
     * <code>.coreapi.service.PatchWebhookRequest.PatchWebhookBody body = 3 [json_name = "body", (.buf.validate.field) = { ... }</code>
     * @return The body.
     */
    public io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody getBody() {
      if (bodyBuilder_ == null) {
        return body_ == null ? io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody.getDefaultInstance() : body_;
      } else {
        return bodyBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Patch body. Only fields listed in update_mask are applied.
     * </pre>
     *
     * <code>.coreapi.service.PatchWebhookRequest.PatchWebhookBody body = 3 [json_name = "body", (.buf.validate.field) = { ... }</code>
     */
    public Builder setBody(io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
      } else {
        bodyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Patch body. Only fields listed in update_mask are applied.
     * </pre>
     *
     * <code>.coreapi.service.PatchWebhookRequest.PatchWebhookBody body = 3 [json_name = "body", (.buf.validate.field) = { ... }</code>
     */
    public Builder setBody(
        io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        body_ = builderForValue.build();
      } else {
        bodyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Patch body. Only fields listed in update_mask are applied.
     * </pre>
     *
     * <code>.coreapi.service.PatchWebhookRequest.PatchWebhookBody body = 3 [json_name = "body", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeBody(io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody value) {
      if (bodyBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          body_ != null &&
          body_ != io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody.getDefaultInstance()) {
          getBodyBuilder().mergeFrom(value);
        } else {
          body_ = value;
        }
      } else {
        bodyBuilder_.mergeFrom(value);
      }
      if (body_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Patch body. Only fields listed in update_mask are applied.
     * </pre>
     *
     * <code>.coreapi.service.PatchWebhookRequest.PatchWebhookBody body = 3 [json_name = "body", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearBody() {
      bitField0_ = (bitField0_ & ~0x00000004);
      body_ = null;
      if (bodyBuilder_ != null) {
        bodyBuilder_.dispose();
        bodyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Patch body. Only fields listed in update_mask are applied.
     * </pre>
     *
     * <code>.coreapi.service.PatchWebhookRequest.PatchWebhookBody body = 3 [json_name = "body", (.buf.validate.field) = { ... }</code>
     */
    public io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody.Builder getBodyBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetBodyFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Patch body. Only fields listed in update_mask are applied.
     * </pre>
     *
     * <code>.coreapi.service.PatchWebhookRequest.PatchWebhookBody body = 3 [json_name = "body", (.buf.validate.field) = { ... }</code>
     */
    public io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBodyOrBuilder getBodyOrBuilder() {
      if (bodyBuilder_ != null) {
        return bodyBuilder_.getMessageOrBuilder();
      } else {
        return body_ == null ?
            io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody.getDefaultInstance() : body_;
      }
    }
    /**
     * <pre>
     * Patch body. Only fields listed in update_mask are applied.
     * </pre>
     *
     * <code>.coreapi.service.PatchWebhookRequest.PatchWebhookBody body = 3 [json_name = "body", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody, io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody.Builder, io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBodyOrBuilder> 
        internalGetBodyFieldBuilder() {
      if (bodyBuilder_ == null) {
        bodyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody, io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody.Builder, io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBodyOrBuilder>(
                getBody(),
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      return bodyBuilder_;
    }

    private com.google.protobuf.FieldMask updateMask_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> updateMaskBuilder_;
    /**
     * <pre>
     * Set of field paths (relative to PatchWebhookBody) to update.
     * Unlisted fields remain unchanged.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 4 [json_name = "updateMask", (.buf.validate.field) = { ... }</code>
     * @return Whether the updateMask field is set.
     */
    public boolean hasUpdateMask() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Set of field paths (relative to PatchWebhookBody) to update.
     * Unlisted fields remain unchanged.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 4 [json_name = "updateMask", (.buf.validate.field) = { ... }</code>
     * @return The updateMask.
     */
    public com.google.protobuf.FieldMask getUpdateMask() {
      if (updateMaskBuilder_ == null) {
        return updateMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : updateMask_;
      } else {
        return updateMaskBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Set of field paths (relative to PatchWebhookBody) to update.
     * Unlisted fields remain unchanged.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 4 [json_name = "updateMask", (.buf.validate.field) = { ... }</code>
     */
    public Builder setUpdateMask(com.google.protobuf.FieldMask value) {
      if (updateMaskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updateMask_ = value;
      } else {
        updateMaskBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Set of field paths (relative to PatchWebhookBody) to update.
     * Unlisted fields remain unchanged.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 4 [json_name = "updateMask", (.buf.validate.field) = { ... }</code>
     */
    public Builder setUpdateMask(
        com.google.protobuf.FieldMask.Builder builderForValue) {
      if (updateMaskBuilder_ == null) {
        updateMask_ = builderForValue.build();
      } else {
        updateMaskBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Set of field paths (relative to PatchWebhookBody) to update.
     * Unlisted fields remain unchanged.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 4 [json_name = "updateMask", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeUpdateMask(com.google.protobuf.FieldMask value) {
      if (updateMaskBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          updateMask_ != null &&
          updateMask_ != com.google.protobuf.FieldMask.getDefaultInstance()) {
          getUpdateMaskBuilder().mergeFrom(value);
        } else {
          updateMask_ = value;
        }
      } else {
        updateMaskBuilder_.mergeFrom(value);
      }
      if (updateMask_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Set of field paths (relative to PatchWebhookBody) to update.
     * Unlisted fields remain unchanged.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 4 [json_name = "updateMask", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearUpdateMask() {
      bitField0_ = (bitField0_ & ~0x00000008);
      updateMask_ = null;
      if (updateMaskBuilder_ != null) {
        updateMaskBuilder_.dispose();
        updateMaskBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Set of field paths (relative to PatchWebhookBody) to update.
     * Unlisted fields remain unchanged.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 4 [json_name = "updateMask", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.FieldMask.Builder getUpdateMaskBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetUpdateMaskFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Set of field paths (relative to PatchWebhookBody) to update.
     * Unlisted fields remain unchanged.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 4 [json_name = "updateMask", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder() {
      if (updateMaskBuilder_ != null) {
        return updateMaskBuilder_.getMessageOrBuilder();
      } else {
        return updateMask_ == null ?
            com.google.protobuf.FieldMask.getDefaultInstance() : updateMask_;
      }
    }
    /**
     * <pre>
     * Set of field paths (relative to PatchWebhookBody) to update.
     * Unlisted fields remain unchanged.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 4 [json_name = "updateMask", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> 
        internalGetUpdateMaskFieldBuilder() {
      if (updateMaskBuilder_ == null) {
        updateMaskBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder>(
                getUpdateMask(),
                getParentForChildren(),
                isClean());
        updateMask_ = null;
      }
      return updateMaskBuilder_;
    }

    /* Generated by protoc-gen-java-set-or-clear */
    
    /**
     * @param value The webhook_id to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearWebhookId(java.lang.String value) {
    	if (value == null)
    		return clearWebhookId();
    	else
    		return setWebhookId(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearWebhookId(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearWebhookId();
    	else
    		return setWebhookId(mapFunc.apply(value));
    }
    	
    /**
     * @param value The channel_id to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearChannelId(java.lang.String value) {
    	if (value == null)
    		return clearChannelId();
    	else
    		return setChannelId(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearChannelId(T value, java.util.function.Function<T, java.lang.String> mapFunc) {
    	if (value == null)
    		return clearChannelId();
    	else
    		return setChannelId(mapFunc.apply(value));
    }
    	
    /**
     * @param value The body to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearBody(io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody value) {
    	if (value == null)
    		return clearBody();
    	else
    		return setBody(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearBody(T value, java.util.function.Function<T, io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest.PatchWebhookBody> mapFunc) {
    	if (value == null)
    		return clearBody();
    	else
    		return setBody(mapFunc.apply(value));
    }
    	
    /**
     * @param value The update_mask to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearUpdateMask(com.google.protobuf.FieldMask value) {
    	if (value == null)
    		return clearUpdateMask();
    	else
    		return setUpdateMask(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearUpdateMask(T value, java.util.function.Function<T, com.google.protobuf.FieldMask> mapFunc) {
    	if (value == null)
    		return clearUpdateMask();
    	else
    		return setUpdateMask(mapFunc.apply(value));
    }
    	
    // @@protoc_insertion_point(builder_scope:coreapi.service.PatchWebhookRequest)
  }

  // @@protoc_insertion_point(class_scope:coreapi.service.PatchWebhookRequest)
  private static final io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest();
  }

  public static io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PatchWebhookRequest>
      PARSER = new com.google.protobuf.AbstractParser<PatchWebhookRequest>() {
    @java.lang.Override
    public PatchWebhookRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PatchWebhookRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PatchWebhookRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.service.PatchWebhookRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}