// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/service/bot.proto

package io.channel.api.proto.coreapi.service;

public interface GetBotRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coreapi.service.GetBotRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bot_id = 1 [json_name = "botId", (.buf.validate.field) = { ... }</code>
   * @return The botId.
   */
  java.lang.String getBotId();
  /**
   * <code>string bot_id = 1 [json_name = "botId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for botId.
   */
  com.google.protobuf.ByteString
      getBotIdBytes();

  /**
   * <code>string channel_id = 2 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The channelId.
   */
  java.lang.String getChannelId();
  /**
   * <code>string channel_id = 2 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for channelId.
   */
  com.google.protobuf.ByteString
      getChannelIdBytes();
}
