// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/app_segment.proto

package io.channel.api.proto.pub.coreapi.model;

public final class AppSegmentOuterClass {
  private AppSegmentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_model_AppSegment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_model_AppSegment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037coreapi/model/app_segment.proto\022\rcorea" +
      "pi.model\032\033buf/validate/validate.proto\"\322\002" +
      "\n\nAppSegment\022d\n\006app_id\030\001 \001(\tBM\272HJ\272\001D\n\rst" +
      "ring.minLen\022\"value must be at least 1 ch" +
      "aracter\032\017size(this) >= 1\310\001\001R\005appId\022p\n\014ex" +
      "tension_id\030\002 \001(\tBM\272HJ\272\001D\n\rstring.minLen\022" +
      "\"value must be at least 1 character\032\017siz" +
      "e(this) >= 1\310\001\001R\013extensionId\022l\n\nsegment_" +
      "id\030\003 \001(\tBM\272HJ\272\001D\n\rstring.minLen\022\"value m" +
      "ust be at least 1 character\032\017size(this) " +
      ">= 1\310\001\001R\tsegmentIdBb\n&io.channel.api.pro" +
      "to.pub.coreapi.modelP\001Z6github.com/chann" +
      "el-io/ch-proto-public/coreapi/go/modelb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
        });
    internal_static_coreapi_model_AppSegment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_coreapi_model_AppSegment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_model_AppSegment_descriptor,
        new java.lang.String[] { "AppId", "ExtensionId", "SegmentId", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    build.buf.validate.ValidateProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
