// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/chat_bookmark.proto

package io.channel.api.proto.pub.coreapi.model;

public final class ChatBookmarkOuterClass {
  private ChatBookmarkOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_model_ChatBookmark_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_model_ChatBookmark_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!coreapi/model/chat_bookmark.proto\022\rcor" +
      "eapi.model\032\033buf/validate/validate.proto\"" +
      "\203\007\n\014ChatBookmark\022_\n\003key\030\001 \001(\tBM\272HJ\272\001D\n\rs" +
      "tring.minLen\022\"value must be at least 1 c" +
      "haracter\032\017size(this) >= 1\310\001\001R\003key\022f\n\007cha" +
      "t_id\030\002 \001(\tBM\272HJ\272\001D\n\rstring.minLen\022\"value" +
      " must be at least 1 character\032\017size(this" +
      ") >= 1\310\001\001R\006chatId\022h\n\010chat_key\030\003 \001(\tBM\272HJ" +
      "\272\001D\n\rstring.minLen\022\"value must be at lea" +
      "st 1 character\032\017size(this) >= 1\310\001\001R\007chat" +
      "Key\022p\n\014bookmark_key\030\004 \001(\tBM\272HJ\272\001D\n\rstrin" +
      "g.minLen\022\"value must be at least 1 chara" +
      "cter\032\017size(this) >= 1\310\001\001R\013bookmarkKey\022l\n" +
      "\nchannel_id\030\005 \001(\tBM\272HJ\272\001D\n\rstring.minLen" +
      "\022\"value must be at least 1 character\032\017si" +
      "ze(this) >= 1\310\001\001R\tchannelId\022\030\n\007version\030\006" +
      " \001(\003R\007version\022n\n\013person_type\030\007 \001(\tBM\272HJ\272" +
      "\001D\n\rstring.minLen\022\"value must be at leas" +
      "t 1 character\032\017size(this) >= 1\310\001\001R\nperso" +
      "nType\022j\n\tperson_id\030\010 \001(\tBM\272HJ\272\001D\n\rstring" +
      ".minLen\022\"value must be at least 1 charac" +
      "ter\032\017size(this) >= 1\310\001\001R\010personId\022j\n\tcha" +
      "t_type\030\t \001(\tBM\272HJ\272\001D\n\rstring.minLen\022\"val" +
      "ue must be at least 1 character\032\017size(th" +
      "is) >= 1\310\001\001R\010chatTypeBb\n&io.channel.api." +
      "proto.pub.coreapi.modelP\001Z6github.com/ch" +
      "annel-io/ch-proto-public/coreapi/go/mode" +
      "lb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
        });
    internal_static_coreapi_model_ChatBookmark_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_coreapi_model_ChatBookmark_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_model_ChatBookmark_descriptor,
        new java.lang.String[] { "Key", "ChatId", "ChatKey", "BookmarkKey", "ChannelId", "Version", "PersonType", "PersonId", "ChatType", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    build.buf.validate.ValidateProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
