// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/chat_tag.proto

package io.channel.api.proto.pub.coreapi.model;

/**
 * <pre>
 * Color variant for visual labeling of chat tags.
 * </pre>
 *
 * Protobuf enum {@code coreapi.model.ChatTagColorVariant}
 */
public enum ChatTagColorVariant
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_UNSPECIFIED = 0;</code>
   */
  CHAT_TAG_COLOR_VARIANT_UNSPECIFIED(0),
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_RED = 1;</code>
   */
  CHAT_TAG_COLOR_VARIANT_RED(1),
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_ORANGE = 2;</code>
   */
  CHAT_TAG_COLOR_VARIANT_ORANGE(2),
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_YELLOW = 3;</code>
   */
  CHAT_TAG_COLOR_VARIANT_YELLOW(3),
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_OLIVE = 4;</code>
   */
  CHAT_TAG_COLOR_VARIANT_OLIVE(4),
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_GREEN = 5;</code>
   */
  CHAT_TAG_COLOR_VARIANT_GREEN(5),
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_COBALT = 6;</code>
   */
  CHAT_TAG_COLOR_VARIANT_COBALT(6),
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_PURPLE = 7;</code>
   */
  CHAT_TAG_COLOR_VARIANT_PURPLE(7),
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_PINK = 8;</code>
   */
  CHAT_TAG_COLOR_VARIANT_PINK(8),
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_NAVY = 9;</code>
   */
  CHAT_TAG_COLOR_VARIANT_NAVY(9),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CHAT_TAG_COLOR_VARIANT_UNSPECIFIED = 0;</code>
   */
  public static final int CHAT_TAG_COLOR_VARIANT_UNSPECIFIED_VALUE = 0;
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_RED = 1;</code>
   */
  public static final int CHAT_TAG_COLOR_VARIANT_RED_VALUE = 1;
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_ORANGE = 2;</code>
   */
  public static final int CHAT_TAG_COLOR_VARIANT_ORANGE_VALUE = 2;
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_YELLOW = 3;</code>
   */
  public static final int CHAT_TAG_COLOR_VARIANT_YELLOW_VALUE = 3;
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_OLIVE = 4;</code>
   */
  public static final int CHAT_TAG_COLOR_VARIANT_OLIVE_VALUE = 4;
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_GREEN = 5;</code>
   */
  public static final int CHAT_TAG_COLOR_VARIANT_GREEN_VALUE = 5;
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_COBALT = 6;</code>
   */
  public static final int CHAT_TAG_COLOR_VARIANT_COBALT_VALUE = 6;
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_PURPLE = 7;</code>
   */
  public static final int CHAT_TAG_COLOR_VARIANT_PURPLE_VALUE = 7;
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_PINK = 8;</code>
   */
  public static final int CHAT_TAG_COLOR_VARIANT_PINK_VALUE = 8;
  /**
   * <code>CHAT_TAG_COLOR_VARIANT_NAVY = 9;</code>
   */
  public static final int CHAT_TAG_COLOR_VARIANT_NAVY_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ChatTagColorVariant valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ChatTagColorVariant forNumber(int value) {
    switch (value) {
      case 0: return CHAT_TAG_COLOR_VARIANT_UNSPECIFIED;
      case 1: return CHAT_TAG_COLOR_VARIANT_RED;
      case 2: return CHAT_TAG_COLOR_VARIANT_ORANGE;
      case 3: return CHAT_TAG_COLOR_VARIANT_YELLOW;
      case 4: return CHAT_TAG_COLOR_VARIANT_OLIVE;
      case 5: return CHAT_TAG_COLOR_VARIANT_GREEN;
      case 6: return CHAT_TAG_COLOR_VARIANT_COBALT;
      case 7: return CHAT_TAG_COLOR_VARIANT_PURPLE;
      case 8: return CHAT_TAG_COLOR_VARIANT_PINK;
      case 9: return CHAT_TAG_COLOR_VARIANT_NAVY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ChatTagColorVariant>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ChatTagColorVariant> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ChatTagColorVariant>() {
          public ChatTagColorVariant findValueByNumber(int number) {
            return ChatTagColorVariant.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.channel.api.proto.pub.coreapi.model.ChatTagOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final ChatTagColorVariant[] VALUES = values();

  public static ChatTagColorVariant valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ChatTagColorVariant(int value) {
    this.value = value;
  }

  /* Generated by protoc-gen-java-canonical-enum-namings */
  
  /**
   * @param value The string value corresponding to the enum entry.
   * @return The enum entry corresponding to the string value.
   */
  public static ChatTagColorVariant forString(String value) {
  	switch (value) {
      case "cobalt": return CHAT_TAG_COLOR_VARIANT_COBALT;
      case "green": return CHAT_TAG_COLOR_VARIANT_GREEN;
      case "navy": return CHAT_TAG_COLOR_VARIANT_NAVY;
      case "olive": return CHAT_TAG_COLOR_VARIANT_OLIVE;
      case "orange": return CHAT_TAG_COLOR_VARIANT_ORANGE;
      case "pink": return CHAT_TAG_COLOR_VARIANT_PINK;
      case "purple": return CHAT_TAG_COLOR_VARIANT_PURPLE;
      case "red": return CHAT_TAG_COLOR_VARIANT_RED;
      case "yellow": return CHAT_TAG_COLOR_VARIANT_YELLOW;
  		default: return CHAT_TAG_COLOR_VARIANT_UNSPECIFIED;
  	}
  }
  				
  /**
   * @return The string value corresponding to the enum entry.
   */
  public final String getString() {
  	switch (this) {
      case CHAT_TAG_COLOR_VARIANT_COBALT: return "cobalt";
      case CHAT_TAG_COLOR_VARIANT_GREEN: return "green";
      case CHAT_TAG_COLOR_VARIANT_NAVY: return "navy";
      case CHAT_TAG_COLOR_VARIANT_OLIVE: return "olive";
      case CHAT_TAG_COLOR_VARIANT_ORANGE: return "orange";
      case CHAT_TAG_COLOR_VARIANT_PINK: return "pink";
      case CHAT_TAG_COLOR_VARIANT_PURPLE: return "purple";
      case CHAT_TAG_COLOR_VARIANT_RED: return "red";
      case CHAT_TAG_COLOR_VARIANT_YELLOW: return "yellow";
  		default: return null;
  	}
  }
  				
  // @@protoc_insertion_point(enum_scope:coreapi.model.ChatTagColorVariant)
}
