// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/event.proto

package io.channel.api.proto.pub.coreapi.model;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coreapi.model.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the user who triggered the event.
   * +kubebuilder:validation:Required
   * +kubebuilder:example="u-abc123"
   * </pre>
   *
   * <code>string user_id = 1 [json_name = "userId", (.buf.validate.field) = { ... }</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * ID of the user who triggered the event.
   * +kubebuilder:validation:Required
   * +kubebuilder:example="u-abc123"
   * </pre>
   *
   * <code>string user_id = 1 [json_name = "userId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * Unique event identifier.
   * +kubebuilder:validation:Required
   * +kubebuilder:example="evt-20240101-001"
   * </pre>
   *
   * <code>string id = 2 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Unique event identifier.
   * +kubebuilder:validation:Required
   * +kubebuilder:example="evt-20240101-001"
   * </pre>
   *
   * <code>string id = 2 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Channel ID this event belongs to.
   * +kubebuilder:validation:Required
   * +kubebuilder:example="ch-12345"
   * </pre>
   *
   * <code>string channel_id = 3 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The channelId.
   */
  java.lang.String getChannelId();
  /**
   * <pre>
   * Channel ID this event belongs to.
   * +kubebuilder:validation:Required
   * +kubebuilder:example="ch-12345"
   * </pre>
   *
   * <code>string channel_id = 3 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for channelId.
   */
  com.google.protobuf.ByteString
      getChannelIdBytes();

  /**
   * <pre>
   * Event name identifying the type of action (e.g., PageView, Purchase, SignUp).
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * +kubebuilder:validation:MaxLength=64
   * +kubebuilder:example="PageView"
   * </pre>
   *
   * <code>string name = 4 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Event name identifying the type of action (e.g., PageView, Purchase, SignUp).
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * +kubebuilder:validation:MaxLength=64
   * +kubebuilder:example="PageView"
   * </pre>
   *
   * <code>string name = 4 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Custom key-value properties associated with the event (e.g., page URL, product ID, revenue).
   * +kubebuilder:example={"url":"/checkout","revenue":50000,"category":"product"}
   * </pre>
   *
   * <code>.google.protobuf.Struct property = 5 [json_name = "property"];</code>
   * @return Whether the property field is set.
   */
  boolean hasProperty();
  /**
   * <pre>
   * Custom key-value properties associated with the event (e.g., page URL, product ID, revenue).
   * +kubebuilder:example={"url":"/checkout","revenue":50000,"category":"product"}
   * </pre>
   *
   * <code>.google.protobuf.Struct property = 5 [json_name = "property"];</code>
   * @return The property.
   */
  com.google.protobuf.Struct getProperty();
  /**
   * <pre>
   * Custom key-value properties associated with the event (e.g., page URL, product ID, revenue).
   * +kubebuilder:example={"url":"/checkout","revenue":50000,"category":"product"}
   * </pre>
   *
   * <code>.google.protobuf.Struct property = 5 [json_name = "property"];</code>
   */
  com.google.protobuf.StructOrBuilder getPropertyOrBuilder();

  /**
   * <pre>
   * Event creation timestamp.
   * +kubebuilder:validation:Required
   * +kubebuilder:example="2026-04-28T09:30:00Z"
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <pre>
   * Event creation timestamp.
   * +kubebuilder:validation:Required
   * +kubebuilder:example="2026-04-28T09:30:00Z"
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <pre>
   * Event creation timestamp.
   * +kubebuilder:validation:Required
   * +kubebuilder:example="2026-04-28T09:30:00Z"
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <pre>
   * Expiration timestamp after which the event may no longer be retrievable.
   * +kubebuilder:example="2026-04-28T09:30:00Z"
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expire_at = 7 [json_name = "expireAt"];</code>
   * @return Whether the expireAt field is set.
   */
  boolean hasExpireAt();
  /**
   * <pre>
   * Expiration timestamp after which the event may no longer be retrievable.
   * +kubebuilder:example="2026-04-28T09:30:00Z"
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expire_at = 7 [json_name = "expireAt"];</code>
   * @return The expireAt.
   */
  com.google.protobuf.Timestamp getExpireAt();
  /**
   * <pre>
   * Expiration timestamp after which the event may no longer be retrievable.
   * +kubebuilder:example="2026-04-28T09:30:00Z"
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expire_at = 7 [json_name = "expireAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpireAtOrBuilder();

  /**
   * <pre>
   * Optimistic concurrency version counter.
   * Incremented on each update to detect conflicting writes.
   * +kubebuilder:example="1"
   * </pre>
   *
   * <code>int64 version = 8 [json_name = "version"];</code>
   * @return The version.
   */
  long getVersion();

  /**
   * <pre>
   * Internationalized event name map keyed by locale (e.g., en, ko).
   * Populated only for system-defined events; custom events return no entries.
   * +kubebuilder:example={"ko":"페이지뷰","en":"PageView"}
   * </pre>
   *
   * <code>map&lt;string, string&gt; name_i18n_map = 9 [json_name = "nameI18nMap"];</code>
   */
  int getNameI18NMapCount();
  /**
   * <pre>
   * Internationalized event name map keyed by locale (e.g., en, ko).
   * Populated only for system-defined events; custom events return no entries.
   * +kubebuilder:example={"ko":"페이지뷰","en":"PageView"}
   * </pre>
   *
   * <code>map&lt;string, string&gt; name_i18n_map = 9 [json_name = "nameI18nMap"];</code>
   */
  boolean containsNameI18NMap(
      java.lang.String key);
  /**
   * Use {@link #getNameI18NMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getNameI18NMap();
  /**
   * <pre>
   * Internationalized event name map keyed by locale (e.g., en, ko).
   * Populated only for system-defined events; custom events return no entries.
   * +kubebuilder:example={"ko":"페이지뷰","en":"PageView"}
   * </pre>
   *
   * <code>map&lt;string, string&gt; name_i18n_map = 9 [json_name = "nameI18nMap"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getNameI18NMapMap();
  /**
   * <pre>
   * Internationalized event name map keyed by locale (e.g., en, ko).
   * Populated only for system-defined events; custom events return no entries.
   * +kubebuilder:example={"ko":"페이지뷰","en":"PageView"}
   * </pre>
   *
   * <code>map&lt;string, string&gt; name_i18n_map = 9 [json_name = "nameI18nMap"];</code>
   */

  java.lang.String getNameI18NMapOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <pre>
   * Internationalized event name map keyed by locale (e.g., en, ko).
   * Populated only for system-defined events; custom events return no entries.
   * +kubebuilder:example={"ko":"페이지뷰","en":"PageView"}
   * </pre>
   *
   * <code>map&lt;string, string&gt; name_i18n_map = 9 [json_name = "nameI18nMap"];</code>
   */

  java.lang.String getNameI18NMapOrThrow(
      java.lang.String key);
}
