// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/image_file.proto

package io.channel.api.proto.pub.coreapi.model;

public final class ImageFileOuterClass {
  private ImageFileOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_model_ImageFile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_model_ImageFile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036coreapi/model/image_file.proto\022\rcoreap" +
      "i.model\032\033buf/validate/validate.proto\"\266\002\n" +
      "\tImageFile\022e\n\006bucket\030\001 \001(\tBM\272HJ\272\001D\n\rstri" +
      "ng.minLen\022\"value must be at least 1 char" +
      "acter\032\017size(this) >= 1\310\001\001R\006bucket\022_\n\003key" +
      "\030\002 \001(\tBM\272HJ\272\001D\n\rstring.minLen\022\"value mus" +
      "t be at least 1 character\032\017size(this) >=" +
      " 1\310\001\001R\003key\022\024\n\005width\030\003 \001(\005R\005width\022\026\n\006heig" +
      "ht\030\004 \001(\005R\006height\0223\n\014content_type\030\005 \001(\tB\020" +
      "\272H\rr\0132\t^image/.*R\013contentTypeBb\n&io.chan" +
      "nel.api.proto.pub.coreapi.modelP\001Z6githu" +
      "b.com/channel-io/ch-proto-public/coreapi" +
      "/go/modelb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
        });
    internal_static_coreapi_model_ImageFile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_coreapi_model_ImageFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_model_ImageFile_descriptor,
        new java.lang.String[] { "Bucket", "Key", "Width", "Height", "ContentType", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    build.buf.validate.ValidateProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
