// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/message_content.proto

package io.channel.api.proto.pub.coreapi.model;

public interface MessageButtonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coreapi.model.MessageButton)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Button label shown to the user.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * +kubebuilder:validation:MaxLength=30
   * +kubebuilder:example="Learn More"
   * </pre>
   *
   * <code>string title = 1 [json_name = "title", (.buf.validate.field) = { ... }</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * Button label shown to the user.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * +kubebuilder:validation:MaxLength=30
   * +kubebuilder:example="Learn More"
   * </pre>
   *
   * <code>string title = 1 [json_name = "title", (.buf.validate.field) = { ... }</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * Visual color theme applied to the button.
   * Defaults to the channel's primary color when not specified.
   * </pre>
   *
   * <code>.coreapi.model.MessageButton.ColorVariant color_variant = 2 [json_name = "colorVariant"];</code>
   * @return The enum numeric value on the wire for colorVariant.
   */
  int getColorVariantValue();
  /**
   * <pre>
   * Visual color theme applied to the button.
   * Defaults to the channel's primary color when not specified.
   * </pre>
   *
   * <code>.coreapi.model.MessageButton.ColorVariant color_variant = 2 [json_name = "colorVariant"];</code>
   * @return The colorVariant.
   */
  io.channel.api.proto.pub.coreapi.model.MessageButton.ColorVariant getColorVariant();

  /**
   * <pre>
   * Action payload executed when the button is clicked.
   * Contains the action type and its attributes (e.g. URL to open, WAM to launch).
   * +kubebuilder:validation:Required
   * +kubebuilder:example={"type":"web","attributes":{"url":"https://channel.io"}}
   * </pre>
   *
   * <code>.google.protobuf.Struct action = 3 [json_name = "action", (.buf.validate.field) = { ... }</code>
   * @return Whether the action field is set.
   */
  boolean hasAction();
  /**
   * <pre>
   * Action payload executed when the button is clicked.
   * Contains the action type and its attributes (e.g. URL to open, WAM to launch).
   * +kubebuilder:validation:Required
   * +kubebuilder:example={"type":"web","attributes":{"url":"https://channel.io"}}
   * </pre>
   *
   * <code>.google.protobuf.Struct action = 3 [json_name = "action", (.buf.validate.field) = { ... }</code>
   * @return The action.
   */
  com.google.protobuf.Struct getAction();
  /**
   * <pre>
   * Action payload executed when the button is clicked.
   * Contains the action type and its attributes (e.g. URL to open, WAM to launch).
   * +kubebuilder:validation:Required
   * +kubebuilder:example={"type":"web","attributes":{"url":"https://channel.io"}}
   * </pre>
   *
   * <code>.google.protobuf.Struct action = 3 [json_name = "action", (.buf.validate.field) = { ... }</code>
   */
  com.google.protobuf.StructOrBuilder getActionOrBuilder();
}
