// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/message_button.proto

package io.channel.api.proto.pub.coreapi.model;

public final class MessageButtonOuterClass {
  private MessageButtonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_model_MessageButton_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_model_MessageButton_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"coreapi/model/message_button.proto\022\rco" +
      "reapi.model\032\033buf/validate/validate.proto" +
      "\032\034google/protobuf/struct.proto\"\255\004\n\rMessa" +
      "geButton\022\263\001\n\005title\030\001 \001(\tB\234\001\272H\230\001\272\001D\n\rstri" +
      "ng.minLen\022\"value must be at least 1 char" +
      "acter\032\017size(this) >= 1\272\001K\n\rstring.maxLen" +
      "\022(value must be no more than 30 characte" +
      "rs\032\020size(this) <= 30\310\001\001R\005title\022N\n\rcolor_" +
      "variant\030\002 \001(\0162).coreapi.model.MessageBut" +
      "ton.ColorVariantR\014colorVariant\0227\n\006action" +
      "\030\003 \001(\0132\027.google.protobuf.StructB\006\272H\003\310\001\001R" +
      "\006action\"\334\001\n\014ColorVariant\022\035\n\031COLOR_VARIAN" +
      "T_UNSPECIFIED\020\000\022\030\n\024COLOR_VARIANT_COBALT\020" +
      "\001\022\027\n\023COLOR_VARIANT_GREEN\020\002\022\030\n\024COLOR_VARI" +
      "ANT_ORANGE\020\003\022\025\n\021COLOR_VARIANT_RED\020\004\022\027\n\023C" +
      "OLOR_VARIANT_BLACK\020\005\022\026\n\022COLOR_VARIANT_PI" +
      "NK\020\006\022\030\n\024COLOR_VARIANT_PURPLE\020\007Bb\n&io.cha" +
      "nnel.api.proto.pub.coreapi.modelP\001Z6gith" +
      "ub.com/channel-io/ch-proto-public/coreap" +
      "i/go/modelb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_coreapi_model_MessageButton_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_coreapi_model_MessageButton_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_model_MessageButton_descriptor,
        new java.lang.String[] { "Title", "ColorVariant", "Action", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
