// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/message.proto

package io.channel.api.proto.pub.coreapi.model;

/**
 * <pre>
 * MessageCustomPayload carries messenger-specific data for external integrations
 * (e.g. Kakao, LINE) that require platform-native message formats.
 * </pre>
 *
 * Protobuf type {@code coreapi.model.MessageCustomPayload}
 */
public final class MessageCustomPayload extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coreapi.model.MessageCustomPayload)
    MessageCustomPayloadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageCustomPayload.newBuilder() to construct.
  private MessageCustomPayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageCustomPayload() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageCustomPayload();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageCustomPayload(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Struct.Builder subBuilder = null;
            if (data_ != null) {
              subBuilder = data_.toBuilder();
            }
            data_ = input.readMessage(com.google.protobuf.Struct.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(data_);
              data_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              paramMapper_ = com.google.protobuf.MapField.newMapField(
                  ParamMapperDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            paramMapper__ = input.readMessage(
                ParamMapperDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            paramMapper_.getMutableMap().put(
                paramMapper__.getKey(), paramMapper__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.channel.api.proto.pub.coreapi.model.MessageOuterClass.internal_static_coreapi_model_MessageCustomPayload_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetParamMapper();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.channel.api.proto.pub.coreapi.model.MessageOuterClass.internal_static_coreapi_model_MessageCustomPayload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.channel.api.proto.pub.coreapi.model.MessageCustomPayload.class, io.channel.api.proto.pub.coreapi.model.MessageCustomPayload.Builder.class);
  }

  public static final int DATA_FIELD_NUMBER = 1;
  private com.google.protobuf.Struct data_;
  /**
   * <pre>
   * Arbitrary JSON payload conforming to the external messenger's message schema.
   * +kubebuilder:example={"type":"customCard","title":"Order Update","body":"Your order has shipped."}
   * </pre>
   *
   * <code>.google.protobuf.Struct data = 1 [json_name = "data"];</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <pre>
   * Arbitrary JSON payload conforming to the external messenger's message schema.
   * +kubebuilder:example={"type":"customCard","title":"Order Update","body":"Your order has shipped."}
   * </pre>
   *
   * <code>.google.protobuf.Struct data = 1 [json_name = "data"];</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getData() {
    return data_ == null ? com.google.protobuf.Struct.getDefaultInstance() : data_;
  }
  /**
   * <pre>
   * Arbitrary JSON payload conforming to the external messenger's message schema.
   * +kubebuilder:example={"type":"customCard","title":"Order Update","body":"Your order has shipped."}
   * </pre>
   *
   * <code>.google.protobuf.Struct data = 1 [json_name = "data"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getDataOrBuilder() {
    return getData();
  }

  public static final int PARAM_MAPPER_FIELD_NUMBER = 2;
  private static final class ParamMapperDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                io.channel.api.proto.pub.coreapi.model.MessageOuterClass.internal_static_coreapi_model_MessageCustomPayload_ParamMapperEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> paramMapper_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetParamMapper() {
    if (paramMapper_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ParamMapperDefaultEntryHolder.defaultEntry);
    }
    return paramMapper_;
  }

  public int getParamMapperCount() {
    return internalGetParamMapper().getMap().size();
  }
  /**
   * <pre>
   * Key-value mapping for template variable substitution within the custom payload.
   * Keys are placeholder names and values are the replacement strings.
   * +kubebuilder:example={"customer_name":"{{user.profile.name}}","order_id":"{{event.orderId}}"}
   * </pre>
   *
   * <code>map&lt;string, string&gt; param_mapper = 2 [json_name = "paramMapper"];</code>
   */

  @java.lang.Override
  public boolean containsParamMapper(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetParamMapper().getMap().containsKey(key);
  }
  /**
   * Use {@link #getParamMapperMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getParamMapper() {
    return getParamMapperMap();
  }
  /**
   * <pre>
   * Key-value mapping for template variable substitution within the custom payload.
   * Keys are placeholder names and values are the replacement strings.
   * +kubebuilder:example={"customer_name":"{{user.profile.name}}","order_id":"{{event.orderId}}"}
   * </pre>
   *
   * <code>map&lt;string, string&gt; param_mapper = 2 [json_name = "paramMapper"];</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getParamMapperMap() {
    return internalGetParamMapper().getMap();
  }
  /**
   * <pre>
   * Key-value mapping for template variable substitution within the custom payload.
   * Keys are placeholder names and values are the replacement strings.
   * +kubebuilder:example={"customer_name":"{{user.profile.name}}","order_id":"{{event.orderId}}"}
   * </pre>
   *
   * <code>map&lt;string, string&gt; param_mapper = 2 [json_name = "paramMapper"];</code>
   */
  @java.lang.Override

  public java.lang.String getParamMapperOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetParamMapper().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Key-value mapping for template variable substitution within the custom payload.
   * Keys are placeholder names and values are the replacement strings.
   * +kubebuilder:example={"customer_name":"{{user.profile.name}}","order_id":"{{event.orderId}}"}
   * </pre>
   *
   * <code>map&lt;string, string&gt; param_mapper = 2 [json_name = "paramMapper"];</code>
   */
  @java.lang.Override

  public java.lang.String getParamMapperOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetParamMapper().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (data_ != null) {
      output.writeMessage(1, getData());
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetParamMapper(),
        ParamMapperDefaultEntryHolder.defaultEntry,
        2);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getData());
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetParamMapper().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      paramMapper__ = ParamMapperDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, paramMapper__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.channel.api.proto.pub.coreapi.model.MessageCustomPayload)) {
      return super.equals(obj);
    }
    io.channel.api.proto.pub.coreapi.model.MessageCustomPayload other = (io.channel.api.proto.pub.coreapi.model.MessageCustomPayload) obj;

    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (!internalGetParamMapper().equals(
        other.internalGetParamMapper())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    if (!internalGetParamMapper().getMap().isEmpty()) {
      hash = (37 * hash) + PARAM_MAPPER_FIELD_NUMBER;
      hash = (53 * hash) + internalGetParamMapper().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.channel.api.proto.pub.coreapi.model.MessageCustomPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageCustomPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageCustomPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageCustomPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageCustomPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageCustomPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageCustomPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageCustomPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageCustomPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageCustomPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageCustomPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.model.MessageCustomPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.channel.api.proto.pub.coreapi.model.MessageCustomPayload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * MessageCustomPayload carries messenger-specific data for external integrations
   * (e.g. Kakao, LINE) that require platform-native message formats.
   * </pre>
   *
   * Protobuf type {@code coreapi.model.MessageCustomPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coreapi.model.MessageCustomPayload)
      io.channel.api.proto.pub.coreapi.model.MessageCustomPayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.channel.api.proto.pub.coreapi.model.MessageOuterClass.internal_static_coreapi_model_MessageCustomPayload_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetParamMapper();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableParamMapper();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.channel.api.proto.pub.coreapi.model.MessageOuterClass.internal_static_coreapi_model_MessageCustomPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.channel.api.proto.pub.coreapi.model.MessageCustomPayload.class, io.channel.api.proto.pub.coreapi.model.MessageCustomPayload.Builder.class);
    }

    // Construct using io.channel.api.proto.pub.coreapi.model.MessageCustomPayload.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (dataBuilder_ == null) {
        data_ = null;
      } else {
        data_ = null;
        dataBuilder_ = null;
      }
      internalGetMutableParamMapper().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.channel.api.proto.pub.coreapi.model.MessageOuterClass.internal_static_coreapi_model_MessageCustomPayload_descriptor;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.MessageCustomPayload getDefaultInstanceForType() {
      return io.channel.api.proto.pub.coreapi.model.MessageCustomPayload.getDefaultInstance();
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.MessageCustomPayload build() {
      io.channel.api.proto.pub.coreapi.model.MessageCustomPayload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.MessageCustomPayload buildPartial() {
      io.channel.api.proto.pub.coreapi.model.MessageCustomPayload result = new io.channel.api.proto.pub.coreapi.model.MessageCustomPayload(this);
      int from_bitField0_ = bitField0_;
      if (dataBuilder_ == null) {
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      result.paramMapper_ = internalGetParamMapper();
      result.paramMapper_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.channel.api.proto.pub.coreapi.model.MessageCustomPayload) {
        return mergeFrom((io.channel.api.proto.pub.coreapi.model.MessageCustomPayload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.channel.api.proto.pub.coreapi.model.MessageCustomPayload other) {
      if (other == io.channel.api.proto.pub.coreapi.model.MessageCustomPayload.getDefaultInstance()) return this;
      if (other.hasData()) {
        mergeData(other.getData());
      }
      internalGetMutableParamMapper().mergeFrom(
          other.internalGetParamMapper());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.channel.api.proto.pub.coreapi.model.MessageCustomPayload parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.channel.api.proto.pub.coreapi.model.MessageCustomPayload) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Struct data_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> dataBuilder_;
    /**
     * <pre>
     * Arbitrary JSON payload conforming to the external messenger's message schema.
     * +kubebuilder:example={"type":"customCard","title":"Order Update","body":"Your order has shipped."}
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 1 [json_name = "data"];</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return dataBuilder_ != null || data_ != null;
    }
    /**
     * <pre>
     * Arbitrary JSON payload conforming to the external messenger's message schema.
     * +kubebuilder:example={"type":"customCard","title":"Order Update","body":"Your order has shipped."}
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 1 [json_name = "data"];</code>
     * @return The data.
     */
    public com.google.protobuf.Struct getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? com.google.protobuf.Struct.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Arbitrary JSON payload conforming to the external messenger's message schema.
     * +kubebuilder:example={"type":"customCard","title":"Order Update","body":"Your order has shipped."}
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 1 [json_name = "data"];</code>
     */
    public Builder setData(com.google.protobuf.Struct value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Arbitrary JSON payload conforming to the external messenger's message schema.
     * +kubebuilder:example={"type":"customCard","title":"Order Update","body":"Your order has shipped."}
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 1 [json_name = "data"];</code>
     */
    public Builder setData(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Arbitrary JSON payload conforming to the external messenger's message schema.
     * +kubebuilder:example={"type":"customCard","title":"Order Update","body":"Your order has shipped."}
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 1 [json_name = "data"];</code>
     */
    public Builder mergeData(com.google.protobuf.Struct value) {
      if (dataBuilder_ == null) {
        if (data_ != null) {
          data_ =
            com.google.protobuf.Struct.newBuilder(data_).mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        dataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Arbitrary JSON payload conforming to the external messenger's message schema.
     * +kubebuilder:example={"type":"customCard","title":"Order Update","body":"Your order has shipped."}
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 1 [json_name = "data"];</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = null;
        onChanged();
      } else {
        data_ = null;
        dataBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Arbitrary JSON payload conforming to the external messenger's message schema.
     * +kubebuilder:example={"type":"customCard","title":"Order Update","body":"Your order has shipped."}
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 1 [json_name = "data"];</code>
     */
    public com.google.protobuf.Struct.Builder getDataBuilder() {
      
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Arbitrary JSON payload conforming to the external messenger's message schema.
     * +kubebuilder:example={"type":"customCard","title":"Order Update","body":"Your order has shipped."}
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 1 [json_name = "data"];</code>
     */
    public com.google.protobuf.StructOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : data_;
      }
    }
    /**
     * <pre>
     * Arbitrary JSON payload conforming to the external messenger's message schema.
     * +kubebuilder:example={"type":"customCard","title":"Order Update","body":"Your order has shipped."}
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 1 [json_name = "data"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> paramMapper_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetParamMapper() {
      if (paramMapper_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ParamMapperDefaultEntryHolder.defaultEntry);
      }
      return paramMapper_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableParamMapper() {
      onChanged();;
      if (paramMapper_ == null) {
        paramMapper_ = com.google.protobuf.MapField.newMapField(
            ParamMapperDefaultEntryHolder.defaultEntry);
      }
      if (!paramMapper_.isMutable()) {
        paramMapper_ = paramMapper_.copy();
      }
      return paramMapper_;
    }

    public int getParamMapperCount() {
      return internalGetParamMapper().getMap().size();
    }
    /**
     * <pre>
     * Key-value mapping for template variable substitution within the custom payload.
     * Keys are placeholder names and values are the replacement strings.
     * +kubebuilder:example={"customer_name":"{{user.profile.name}}","order_id":"{{event.orderId}}"}
     * </pre>
     *
     * <code>map&lt;string, string&gt; param_mapper = 2 [json_name = "paramMapper"];</code>
     */

    @java.lang.Override
    public boolean containsParamMapper(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetParamMapper().getMap().containsKey(key);
    }
    /**
     * Use {@link #getParamMapperMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getParamMapper() {
      return getParamMapperMap();
    }
    /**
     * <pre>
     * Key-value mapping for template variable substitution within the custom payload.
     * Keys are placeholder names and values are the replacement strings.
     * +kubebuilder:example={"customer_name":"{{user.profile.name}}","order_id":"{{event.orderId}}"}
     * </pre>
     *
     * <code>map&lt;string, string&gt; param_mapper = 2 [json_name = "paramMapper"];</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getParamMapperMap() {
      return internalGetParamMapper().getMap();
    }
    /**
     * <pre>
     * Key-value mapping for template variable substitution within the custom payload.
     * Keys are placeholder names and values are the replacement strings.
     * +kubebuilder:example={"customer_name":"{{user.profile.name}}","order_id":"{{event.orderId}}"}
     * </pre>
     *
     * <code>map&lt;string, string&gt; param_mapper = 2 [json_name = "paramMapper"];</code>
     */
    @java.lang.Override

    public java.lang.String getParamMapperOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetParamMapper().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Key-value mapping for template variable substitution within the custom payload.
     * Keys are placeholder names and values are the replacement strings.
     * +kubebuilder:example={"customer_name":"{{user.profile.name}}","order_id":"{{event.orderId}}"}
     * </pre>
     *
     * <code>map&lt;string, string&gt; param_mapper = 2 [json_name = "paramMapper"];</code>
     */
    @java.lang.Override

    public java.lang.String getParamMapperOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetParamMapper().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearParamMapper() {
      internalGetMutableParamMapper().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * Key-value mapping for template variable substitution within the custom payload.
     * Keys are placeholder names and values are the replacement strings.
     * +kubebuilder:example={"customer_name":"{{user.profile.name}}","order_id":"{{event.orderId}}"}
     * </pre>
     *
     * <code>map&lt;string, string&gt; param_mapper = 2 [json_name = "paramMapper"];</code>
     */

    public Builder removeParamMapper(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableParamMapper().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableParamMapper() {
      return internalGetMutableParamMapper().getMutableMap();
    }
    /**
     * <pre>
     * Key-value mapping for template variable substitution within the custom payload.
     * Keys are placeholder names and values are the replacement strings.
     * +kubebuilder:example={"customer_name":"{{user.profile.name}}","order_id":"{{event.orderId}}"}
     * </pre>
     *
     * <code>map&lt;string, string&gt; param_mapper = 2 [json_name = "paramMapper"];</code>
     */
    public Builder putParamMapper(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableParamMapper().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * Key-value mapping for template variable substitution within the custom payload.
     * Keys are placeholder names and values are the replacement strings.
     * +kubebuilder:example={"customer_name":"{{user.profile.name}}","order_id":"{{event.orderId}}"}
     * </pre>
     *
     * <code>map&lt;string, string&gt; param_mapper = 2 [json_name = "paramMapper"];</code>
     */

    public Builder putAllParamMapper(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableParamMapper().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    /* Generated by protoc-gen-java-set-or-clear */
    
    /**
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearData(com.google.protobuf.Struct value) {
    	if (value == null)
    		return clearData();
    	else
    		return setData(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearData(T value, java.util.function.Function<T, com.google.protobuf.Struct> mapFunc) {
    	if (value == null)
    		return clearData();
    	else
    		return setData(mapFunc.apply(value));
    }
    	
    /**
     * @param map The map to put.
     * @return This builder for chaining.
     */
    public Builder putAllOrClearParamMapper(java.util.Map<java.lang.String, java.lang.String> map) {
    	if (map == null)
    		return clearParamMapper();
    	else
    		return putAllParamMapper(map);
    }
    	
    // @@protoc_insertion_point(builder_scope:coreapi.model.MessageCustomPayload)
  }

  // @@protoc_insertion_point(class_scope:coreapi.model.MessageCustomPayload)
  private static final io.channel.api.proto.pub.coreapi.model.MessageCustomPayload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.channel.api.proto.pub.coreapi.model.MessageCustomPayload();
  }

  public static io.channel.api.proto.pub.coreapi.model.MessageCustomPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageCustomPayload>
      PARSER = new com.google.protobuf.AbstractParser<MessageCustomPayload>() {
    @java.lang.Override
    public MessageCustomPayload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MessageCustomPayload(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageCustomPayload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageCustomPayload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.MessageCustomPayload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
