// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/one_time_msg.proto

package io.channel.api.proto.pub.coreapi.model;

public interface OneTimeMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coreapi.model.OneTimeMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique one-time message identifier.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Unique one-time message identifier.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Channel ID this one-time message belongs to.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string channel_id = 2 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The channelId.
   */
  java.lang.String getChannelId();
  /**
   * <pre>
   * Channel ID this one-time message belongs to.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * </pre>
   *
   * <code>string channel_id = 2 [json_name = "channelId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for channelId.
   */
  com.google.protobuf.ByteString
      getChannelIdBytes();

  /**
   * <pre>
   * Display name of the one-time message.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * +kubebuilder:validation:MaxLength=128
   * </pre>
   *
   * <code>string name = 3 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Display name of the one-time message.
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinLength=1
   * +kubebuilder:validation:MaxLength=128
   * </pre>
   *
   * <code>string name = 3 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Current lifecycle state.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.coreapi.model.OneTimeMsgState state = 4 [json_name = "state", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <pre>
   * Current lifecycle state.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.coreapi.model.OneTimeMsgState state = 4 [json_name = "state", (.buf.validate.field) = { ... }</code>
   * @return The state.
   */
  io.channel.api.proto.pub.coreapi.model.OneTimeMsgState getState();

  /**
   * <pre>
   * Delivery timing mode.
   * Automatically inferred from start_at and local_start_at if not explicitly set.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.OneTimeMsgSendMode send_mode = 5 [json_name = "sendMode"];</code>
   * @return The enum numeric value on the wire for sendMode.
   */
  int getSendModeValue();
  /**
   * <pre>
   * Delivery timing mode.
   * Automatically inferred from start_at and local_start_at if not explicitly set.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.OneTimeMsgSendMode send_mode = 5 [json_name = "sendMode"];</code>
   * @return The sendMode.
   */
  io.channel.api.proto.pub.coreapi.model.OneTimeMsgSendMode getSendMode();

  /**
   * <pre>
   * Channel operation ID for business hours scheduling.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string channel_operation_id = 6 [json_name = "channelOperationId"];</code>
   * @return The channelOperationId.
   */
  java.lang.String getChannelOperationId();
  /**
   * <pre>
   * Channel operation ID for business hours scheduling.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string channel_operation_id = 6 [json_name = "channelOperationId"];</code>
   * @return The bytes for channelOperationId.
   */
  com.google.protobuf.ByteString
      getChannelOperationIdBytes();

  /**
   * <pre>
   * Delivery medium type.
   * May be unset for draft messages.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.MediumType medium_type = 7 [json_name = "mediumType"];</code>
   * @return The enum numeric value on the wire for mediumType.
   */
  int getMediumTypeValue();
  /**
   * <pre>
   * Delivery medium type.
   * May be unset for draft messages.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.coreapi.model.MediumType medium_type = 7 [json_name = "mediumType"];</code>
   * @return The mediumType.
   */
  io.channel.api.proto.pub.coreapi.model.MediumType getMediumType();

  /**
   * <pre>
   * Identifier of the specific medium instance.
   * Required for APP medium type.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string medium_id = 8 [json_name = "mediumId"];</code>
   * @return The mediumId.
   */
  java.lang.String getMediumId();
  /**
   * <pre>
   * Identifier of the specific medium instance.
   * Required for APP medium type.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string medium_id = 8 [json_name = "mediumId"];</code>
   * @return The bytes for mediumId.
   */
  com.google.protobuf.ByteString
      getMediumIdBytes();

  /**
   * <pre>
   * Key for selecting the message topic template within the medium.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string medium_topic_build_key = 9 [json_name = "mediumTopicBuildKey"];</code>
   * @return The mediumTopicBuildKey.
   */
  java.lang.String getMediumTopicBuildKey();
  /**
   * <pre>
   * Key for selecting the message topic template within the medium.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string medium_topic_build_key = 9 [json_name = "mediumTopicBuildKey"];</code>
   * @return The bytes for mediumTopicBuildKey.
   */
  com.google.protobuf.ByteString
      getMediumTopicBuildKeyBytes();

  /**
   * <pre>
   * Labels for categorizing the message topic within the medium.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated string medium_topic_build_labels = 10 [json_name = "mediumTopicBuildLabels"];</code>
   * @return A list containing the mediumTopicBuildLabels.
   */
  java.util.List<java.lang.String>
      getMediumTopicBuildLabelsList();
  /**
   * <pre>
   * Labels for categorizing the message topic within the medium.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated string medium_topic_build_labels = 10 [json_name = "mediumTopicBuildLabels"];</code>
   * @return The count of mediumTopicBuildLabels.
   */
  int getMediumTopicBuildLabelsCount();
  /**
   * <pre>
   * Labels for categorizing the message topic within the medium.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated string medium_topic_build_labels = 10 [json_name = "mediumTopicBuildLabels"];</code>
   * @param index The index of the element to return.
   * @return The mediumTopicBuildLabels at the given index.
   */
  java.lang.String getMediumTopicBuildLabels(int index);
  /**
   * <pre>
   * Labels for categorizing the message topic within the medium.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated string medium_topic_build_labels = 10 [json_name = "mediumTopicBuildLabels"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the mediumTopicBuildLabels at the given index.
   */
  com.google.protobuf.ByteString
      getMediumTopicBuildLabelsBytes(int index);

  /**
   * <pre>
   * Delivery configuration specific to the chosen medium type.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct settings = 12 [json_name = "settings"];</code>
   * @return Whether the settings field is set.
   */
  boolean hasSettings();
  /**
   * <pre>
   * Delivery configuration specific to the chosen medium type.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct settings = 12 [json_name = "settings"];</code>
   * @return The settings.
   */
  com.google.protobuf.Struct getSettings();
  /**
   * <pre>
   * Delivery configuration specific to the chosen medium type.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct settings = 12 [json_name = "settings"];</code>
   */
  com.google.protobuf.StructOrBuilder getSettingsOrBuilder();

  /**
   * <pre>
   * User targeting query for audience filtering.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct user_query = 13 [json_name = "userQuery"];</code>
   * @return Whether the userQuery field is set.
   */
  boolean hasUserQuery();
  /**
   * <pre>
   * User targeting query for audience filtering.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct user_query = 13 [json_name = "userQuery"];</code>
   * @return The userQuery.
   */
  com.google.protobuf.Struct getUserQuery();
  /**
   * <pre>
   * User targeting query for audience filtering.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct user_query = 13 [json_name = "userQuery"];</code>
   */
  com.google.protobuf.StructOrBuilder getUserQueryOrBuilder();

  /**
   * <pre>
   * Conversion tracking windows keyed by feature name.
   * Defaults to 1 day for views and 7 days for clicks.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Duration&gt; conversion_windows = 14 [json_name = "conversionWindows"];</code>
   */
  int getConversionWindowsCount();
  /**
   * <pre>
   * Conversion tracking windows keyed by feature name.
   * Defaults to 1 day for views and 7 days for clicks.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Duration&gt; conversion_windows = 14 [json_name = "conversionWindows"];</code>
   */
  boolean containsConversionWindows(
      java.lang.String key);
  /**
   * Use {@link #getConversionWindowsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.Duration>
  getConversionWindows();
  /**
   * <pre>
   * Conversion tracking windows keyed by feature name.
   * Defaults to 1 day for views and 7 days for clicks.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Duration&gt; conversion_windows = 14 [json_name = "conversionWindows"];</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.Duration>
  getConversionWindowsMap();
  /**
   * <pre>
   * Conversion tracking windows keyed by feature name.
   * Defaults to 1 day for views and 7 days for clicks.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Duration&gt; conversion_windows = 14 [json_name = "conversionWindows"];</code>
   */

  com.google.protobuf.Duration getConversionWindowsOrDefault(
      java.lang.String key,
      com.google.protobuf.Duration defaultValue);
  /**
   * <pre>
   * Conversion tracking windows keyed by feature name.
   * Defaults to 1 day for views and 7 days for clicks.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Duration&gt; conversion_windows = 14 [json_name = "conversionWindows"];</code>
   */

  com.google.protobuf.Duration getConversionWindowsOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * Name of the event tracked as a conversion goal.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string goal_event_name = 15 [json_name = "goalEventName"];</code>
   * @return The goalEventName.
   */
  java.lang.String getGoalEventName();
  /**
   * <pre>
   * Name of the event tracked as a conversion goal.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string goal_event_name = 15 [json_name = "goalEventName"];</code>
   * @return The bytes for goalEventName.
   */
  com.google.protobuf.ByteString
      getGoalEventNameBytes();

  /**
   * <pre>
   * Filtering query for the goal event.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct goal_event_query = 16 [json_name = "goalEventQuery"];</code>
   * @return Whether the goalEventQuery field is set.
   */
  boolean hasGoalEventQuery();
  /**
   * <pre>
   * Filtering query for the goal event.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct goal_event_query = 16 [json_name = "goalEventQuery"];</code>
   * @return The goalEventQuery.
   */
  com.google.protobuf.Struct getGoalEventQuery();
  /**
   * <pre>
   * Filtering query for the goal event.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct goal_event_query = 16 [json_name = "goalEventQuery"];</code>
   */
  com.google.protobuf.StructOrBuilder getGoalEventQueryOrBuilder();

  /**
   * <pre>
   * Duration window for goal event tracking.
   * Valid range is 1 to 30 days. Defaults to 7 days.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Duration goal_event_duration = 17 [json_name = "goalEventDuration"];</code>
   * @return Whether the goalEventDuration field is set.
   */
  boolean hasGoalEventDuration();
  /**
   * <pre>
   * Duration window for goal event tracking.
   * Valid range is 1 to 30 days. Defaults to 7 days.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Duration goal_event_duration = 17 [json_name = "goalEventDuration"];</code>
   * @return The goalEventDuration.
   */
  com.google.protobuf.Duration getGoalEventDuration();
  /**
   * <pre>
   * Duration window for goal event tracking.
   * Valid range is 1 to 30 days. Defaults to 7 days.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Duration goal_event_duration = 17 [json_name = "goalEventDuration"];</code>
   */
  com.google.protobuf.DurationOrBuilder getGoalEventDurationOrBuilder();

  /**
   * <pre>
   * Whether this message contains advertising content.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>bool advertising = 18 [json_name = "advertising"];</code>
   * @return The advertising.
   */
  boolean getAdvertising();

  /**
   * <pre>
   * Whether to send via XMS (SMS/LMS/MMS) to offline users.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>bool send_to_offline_xms = 19 [json_name = "sendToOfflineXms"];</code>
   * @return The sendToOfflineXms.
   */
  boolean getSendToOfflineXms();

  /**
   * <pre>
   * Whether to send via email to offline users.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>bool send_to_offline_email = 20 [json_name = "sendToOfflineEmail"];</code>
   * @return The sendToOfflineEmail.
   */
  boolean getSendToOfflineEmail();

  /**
   * <pre>
   * Scheduled send time in UTC.
   * Applicable when send_mode is RESERVED_WITH_SENDER_TIME.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_at = 21 [json_name = "startAt"];</code>
   * @return Whether the startAt field is set.
   */
  boolean hasStartAt();
  /**
   * <pre>
   * Scheduled send time in UTC.
   * Applicable when send_mode is RESERVED_WITH_SENDER_TIME.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_at = 21 [json_name = "startAt"];</code>
   * @return The startAt.
   */
  com.google.protobuf.Timestamp getStartAt();
  /**
   * <pre>
   * Scheduled send time in UTC.
   * Applicable when send_mode is RESERVED_WITH_SENDER_TIME.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_at = 21 [json_name = "startAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartAtOrBuilder();

  /**
   * <pre>
   * Scheduled send time in receiver's local timezone.
   * ISO 8601 date-time without timezone offset.
   * Applicable when send_mode is RESERVED_WITH_RECEIVER_TIME.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string local_start_at = 22 [json_name = "localStartAt"];</code>
   * @return The localStartAt.
   */
  java.lang.String getLocalStartAt();
  /**
   * <pre>
   * Scheduled send time in receiver's local timezone.
   * ISO 8601 date-time without timezone offset.
   * Applicable when send_mode is RESERVED_WITH_RECEIVER_TIME.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>string local_start_at = 22 [json_name = "localStartAt"];</code>
   * @return The bytes for localStartAt.
   */
  com.google.protobuf.ByteString
      getLocalStartAtBytes();

  /**
   * <pre>
   * Draft snapshot of the message saved before activation.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct draft = 23 [json_name = "draft"];</code>
   * @return Whether the draft field is set.
   */
  boolean hasDraft();
  /**
   * <pre>
   * Draft snapshot of the message saved before activation.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct draft = 23 [json_name = "draft"];</code>
   * @return The draft.
   */
  com.google.protobuf.Struct getDraft();
  /**
   * <pre>
   * Draft snapshot of the message saved before activation.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Struct draft = 23 [json_name = "draft"];</code>
   */
  com.google.protobuf.StructOrBuilder getDraftOrBuilder();

  /**
   * <pre>
   * One-time message creation timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 24 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <pre>
   * One-time message creation timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 24 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <pre>
   * One-time message creation timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 24 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <pre>
   * One-time message last update timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 25 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <pre>
   * One-time message last update timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 25 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
   * @return The updatedAt.
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <pre>
   * One-time message last update timestamp.
   * +kubebuilder:validation:Required
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 25 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

  /**
   * <pre>
   * Total number of messages sent.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>int32 sent = 26 [json_name = "sent"];</code>
   * @return The sent.
   */
  int getSent();

  /**
   * <pre>
   * Total number of message views.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>int32 view = 27 [json_name = "view"];</code>
   * @return The view.
   */
  int getView();

  /**
   * <pre>
   * Total number of goal conversions achieved.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>int32 goal = 28 [json_name = "goal"];</code>
   * @return The goal.
   */
  int getGoal();

  /**
   * <pre>
   * Total number of message link clicks.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>int32 click = 29 [json_name = "click"];</code>
   * @return The click.
   */
  int getClick();

  /**
   * <pre>
   * Duration after which the user chat created by this message expires.
   * Defaults to 31 days.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Duration user_chat_expire_duration = 30 [json_name = "userChatExpireDuration"];</code>
   * @return Whether the userChatExpireDuration field is set.
   */
  boolean hasUserChatExpireDuration();
  /**
   * <pre>
   * Duration after which the user chat created by this message expires.
   * Defaults to 31 days.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Duration user_chat_expire_duration = 30 [json_name = "userChatExpireDuration"];</code>
   * @return The userChatExpireDuration.
   */
  com.google.protobuf.Duration getUserChatExpireDuration();
  /**
   * <pre>
   * Duration after which the user chat created by this message expires.
   * Defaults to 31 days.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>.google.protobuf.Duration user_chat_expire_duration = 30 [json_name = "userChatExpireDuration"];</code>
   */
  com.google.protobuf.DurationOrBuilder getUserChatExpireDurationOrBuilder();

  /**
   * <pre>
   * App segments for user targeting.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated .coreapi.model.AppSegment app_segments = 31 [json_name = "appSegments"];</code>
   */
  java.util.List<io.channel.api.proto.pub.coreapi.model.AppSegment> 
      getAppSegmentsList();
  /**
   * <pre>
   * App segments for user targeting.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated .coreapi.model.AppSegment app_segments = 31 [json_name = "appSegments"];</code>
   */
  io.channel.api.proto.pub.coreapi.model.AppSegment getAppSegments(int index);
  /**
   * <pre>
   * App segments for user targeting.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated .coreapi.model.AppSegment app_segments = 31 [json_name = "appSegments"];</code>
   */
  int getAppSegmentsCount();
  /**
   * <pre>
   * App segments for user targeting.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated .coreapi.model.AppSegment app_segments = 31 [json_name = "appSegments"];</code>
   */
  java.util.List<? extends io.channel.api.proto.pub.coreapi.model.AppSegmentOrBuilder> 
      getAppSegmentsOrBuilderList();
  /**
   * <pre>
   * App segments for user targeting.
   * +kubebuilder:validation:Nullable
   * </pre>
   *
   * <code>repeated .coreapi.model.AppSegment app_segments = 31 [json_name = "appSegments"];</code>
   */
  io.channel.api.proto.pub.coreapi.model.AppSegmentOrBuilder getAppSegmentsOrBuilder(
      int index);
}
