// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: coreapi/model/time_range.proto
// Protobuf Java Version: 4.35.1

package io.channel.api.proto.pub.coreapi.model;

/**
 * <pre>
 * TimeRange represents a recurring weekly time window used for scheduling
 * (e.g. operating hours). Defined by selected days and a minute-of-day range.
 * </pre>
 *
 * Protobuf type {@code coreapi.model.TimeRange}
 */
@com.google.protobuf.Generated
public final class TimeRange extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:coreapi.model.TimeRange)
    TimeRangeOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "TimeRange");
  }
  // Use TimeRange.newBuilder() to construct.
  private TimeRange(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TimeRange() {
    dayOfWeeks_ = emptyIntList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.channel.api.proto.pub.coreapi.model.TimeRangeOuterClass.internal_static_coreapi_model_TimeRange_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return io.channel.api.proto.pub.coreapi.model.TimeRangeOuterClass.internal_static_coreapi_model_TimeRange_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.channel.api.proto.pub.coreapi.model.TimeRangeOuterClass.internal_static_coreapi_model_TimeRange_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.channel.api.proto.pub.coreapi.model.TimeRange.class, io.channel.api.proto.pub.coreapi.model.TimeRange.Builder.class);
  }

  /**
   * <pre>
   * Day of the week.
   * </pre>
   *
   * Protobuf enum {@code coreapi.model.TimeRange.DayOfWeek}
   */
  public enum DayOfWeek
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Unspecified or not set.
     * </pre>
     *
     * <code>DAY_OF_WEEK_UNSPECIFIED = 0;</code>
     */
    DAY_OF_WEEK_UNSPECIFIED(0),
    /**
     * <pre>
     * Monday.
     * </pre>
     *
     * <code>DAY_OF_WEEK_MON = 1;</code>
     */
    DAY_OF_WEEK_MON(1),
    /**
     * <pre>
     * Tuesday.
     * </pre>
     *
     * <code>DAY_OF_WEEK_TUE = 2;</code>
     */
    DAY_OF_WEEK_TUE(2),
    /**
     * <pre>
     * Wednesday.
     * </pre>
     *
     * <code>DAY_OF_WEEK_WED = 3;</code>
     */
    DAY_OF_WEEK_WED(3),
    /**
     * <pre>
     * Thursday.
     * </pre>
     *
     * <code>DAY_OF_WEEK_THU = 4;</code>
     */
    DAY_OF_WEEK_THU(4),
    /**
     * <pre>
     * Friday.
     * </pre>
     *
     * <code>DAY_OF_WEEK_FRI = 5;</code>
     */
    DAY_OF_WEEK_FRI(5),
    /**
     * <pre>
     * Saturday.
     * </pre>
     *
     * <code>DAY_OF_WEEK_SAT = 6;</code>
     */
    DAY_OF_WEEK_SAT(6),
    /**
     * <pre>
     * Sunday.
     * </pre>
     *
     * <code>DAY_OF_WEEK_SUN = 7;</code>
     */
    DAY_OF_WEEK_SUN(7),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "DayOfWeek");
    }
    /**
     * <pre>
     * Unspecified or not set.
     * </pre>
     *
     * <code>DAY_OF_WEEK_UNSPECIFIED = 0;</code>
     */
    public static final int DAY_OF_WEEK_UNSPECIFIED_VALUE = 0;
    /**
     * <pre>
     * Monday.
     * </pre>
     *
     * <code>DAY_OF_WEEK_MON = 1;</code>
     */
    public static final int DAY_OF_WEEK_MON_VALUE = 1;
    /**
     * <pre>
     * Tuesday.
     * </pre>
     *
     * <code>DAY_OF_WEEK_TUE = 2;</code>
     */
    public static final int DAY_OF_WEEK_TUE_VALUE = 2;
    /**
     * <pre>
     * Wednesday.
     * </pre>
     *
     * <code>DAY_OF_WEEK_WED = 3;</code>
     */
    public static final int DAY_OF_WEEK_WED_VALUE = 3;
    /**
     * <pre>
     * Thursday.
     * </pre>
     *
     * <code>DAY_OF_WEEK_THU = 4;</code>
     */
    public static final int DAY_OF_WEEK_THU_VALUE = 4;
    /**
     * <pre>
     * Friday.
     * </pre>
     *
     * <code>DAY_OF_WEEK_FRI = 5;</code>
     */
    public static final int DAY_OF_WEEK_FRI_VALUE = 5;
    /**
     * <pre>
     * Saturday.
     * </pre>
     *
     * <code>DAY_OF_WEEK_SAT = 6;</code>
     */
    public static final int DAY_OF_WEEK_SAT_VALUE = 6;
    /**
     * <pre>
     * Sunday.
     * </pre>
     *
     * <code>DAY_OF_WEEK_SUN = 7;</code>
     */
    public static final int DAY_OF_WEEK_SUN_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DayOfWeek valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DayOfWeek forNumber(int value) {
      switch (value) {
        case 0: return DAY_OF_WEEK_UNSPECIFIED;
        case 1: return DAY_OF_WEEK_MON;
        case 2: return DAY_OF_WEEK_TUE;
        case 3: return DAY_OF_WEEK_WED;
        case 4: return DAY_OF_WEEK_THU;
        case 5: return DAY_OF_WEEK_FRI;
        case 6: return DAY_OF_WEEK_SAT;
        case 7: return DAY_OF_WEEK_SUN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DayOfWeek>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DayOfWeek> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DayOfWeek>() {
            public DayOfWeek findValueByNumber(int number) {
              return DayOfWeek.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.channel.api.proto.pub.coreapi.model.TimeRange.getDescriptor().getEnumType(0);
    }

    private static final DayOfWeek[] VALUES = values();

    public static DayOfWeek valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DayOfWeek(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:coreapi.model.TimeRange.DayOfWeek)
  }

  public static final int DAY_OF_WEEKS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList dayOfWeeks_ =
      emptyIntList();
  private static final     com.google.protobuf.Internal.IntListAdapter.IntConverter<
      io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek> dayOfWeeks_converter_ =
          new com.google.protobuf.Internal.IntListAdapter.IntConverter<
              io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek>() {
            public io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek convert(int from) {
              io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek result = io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek.forNumber(from);
              return result == null ? io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek.UNRECOGNIZED : result;
            }
          };
  /**
   * <pre>
   * Days of the week this time range applies to.
   *
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinItems=1
   * no-example: repeated enum (DayOfWeek); OpenAPI array-example emission not yet supported by harness (iter5 abstention)
   * </pre>
   *
   * <code>repeated .coreapi.model.TimeRange.DayOfWeek day_of_weeks = 1 [json_name = "dayOfWeeks", (.buf.validate.field) = { ... }</code>
   * @return A list containing the dayOfWeeks.
   */
  @java.lang.Override
  public java.util.List<io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek> getDayOfWeeksList() {
    return new com.google.protobuf.Internal.IntListAdapter<
        io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek>(dayOfWeeks_, dayOfWeeks_converter_);
  }
  /**
   * <pre>
   * Days of the week this time range applies to.
   *
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinItems=1
   * no-example: repeated enum (DayOfWeek); OpenAPI array-example emission not yet supported by harness (iter5 abstention)
   * </pre>
   *
   * <code>repeated .coreapi.model.TimeRange.DayOfWeek day_of_weeks = 1 [json_name = "dayOfWeeks", (.buf.validate.field) = { ... }</code>
   * @return The count of dayOfWeeks.
   */
  @java.lang.Override
  public int getDayOfWeeksCount() {
    return dayOfWeeks_.size();
  }
  /**
   * <pre>
   * Days of the week this time range applies to.
   *
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinItems=1
   * no-example: repeated enum (DayOfWeek); OpenAPI array-example emission not yet supported by harness (iter5 abstention)
   * </pre>
   *
   * <code>repeated .coreapi.model.TimeRange.DayOfWeek day_of_weeks = 1 [json_name = "dayOfWeeks", (.buf.validate.field) = { ... }</code>
   * @param index The index of the element to return.
   * @return The dayOfWeeks at the given index.
   */
  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek getDayOfWeeks(int index) {
    return dayOfWeeks_converter_.convert(dayOfWeeks_.getInt(index));
  }
  /**
   * <pre>
   * Days of the week this time range applies to.
   *
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinItems=1
   * no-example: repeated enum (DayOfWeek); OpenAPI array-example emission not yet supported by harness (iter5 abstention)
   * </pre>
   *
   * <code>repeated .coreapi.model.TimeRange.DayOfWeek day_of_weeks = 1 [json_name = "dayOfWeeks", (.buf.validate.field) = { ... }</code>
   * @return A list containing the enum numeric values on the wire for dayOfWeeks.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getDayOfWeeksValueList() {
    return dayOfWeeks_;
  }
  /**
   * <pre>
   * Days of the week this time range applies to.
   *
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:MinItems=1
   * no-example: repeated enum (DayOfWeek); OpenAPI array-example emission not yet supported by harness (iter5 abstention)
   * </pre>
   *
   * <code>repeated .coreapi.model.TimeRange.DayOfWeek day_of_weeks = 1 [json_name = "dayOfWeeks", (.buf.validate.field) = { ... }</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of dayOfWeeks at the given index.
   */
  @java.lang.Override
  public int getDayOfWeeksValue(int index) {
    return dayOfWeeks_.getInt(index);
  }
  private int dayOfWeeksMemoizedSerializedSize;

  public static final int FROM_FIELD_NUMBER = 2;
  private int from_ = 0;
  /**
   * <pre>
   * Start time as minutes from midnight. Must be less than `to`.
   *
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:Minimum=0
   * +kubebuilder:validation:Maximum=1440
   * +kubebuilder:example="540"
   * </pre>
   *
   * <code>int32 from = 2 [json_name = "from", (.buf.validate.field) = { ... }</code>
   * @return The from.
   */
  @java.lang.Override
  public int getFrom() {
    return from_;
  }

  public static final int TO_FIELD_NUMBER = 3;
  private int to_ = 0;
  /**
   * <pre>
   * End time as minutes from midnight. Must be greater than `from`.
   *
   * +kubebuilder:validation:Required
   * +kubebuilder:validation:Minimum=0
   * +kubebuilder:validation:Maximum=1440
   * +kubebuilder:example="1080"
   * </pre>
   *
   * <code>int32 to = 3 [json_name = "to", (.buf.validate.field) = { ... }</code>
   * @return The to.
   */
  @java.lang.Override
  public int getTo() {
    return to_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getDayOfWeeksList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(dayOfWeeksMemoizedSerializedSize);
    }
    for (int i = 0; i < dayOfWeeks_.size(); i++) {
      output.writeEnumNoTag(dayOfWeeks_.getInt(i));
    }
    if (from_ != 0) {
      output.writeInt32(2, from_);
    }
    if (to_ != 0) {
      output.writeInt32(3, to_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < dayOfWeeks_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(dayOfWeeks_.getInt(i));
      }
      size += dataSize;
      if (!getDayOfWeeksList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }dayOfWeeksMemoizedSerializedSize = dataSize;
    }
    if (from_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, from_);
    }
    if (to_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, to_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.channel.api.proto.pub.coreapi.model.TimeRange)) {
      return super.equals(obj);
    }
    io.channel.api.proto.pub.coreapi.model.TimeRange other = (io.channel.api.proto.pub.coreapi.model.TimeRange) obj;

    if (!dayOfWeeks_.equals(other.dayOfWeeks_)) return false;
    if (getFrom()
        != other.getFrom()) return false;
    if (getTo()
        != other.getTo()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDayOfWeeksCount() > 0) {
      hash = (37 * hash) + DAY_OF_WEEKS_FIELD_NUMBER;
      hash = (53 * hash) + dayOfWeeks_.hashCode();
    }
    hash = (37 * hash) + FROM_FIELD_NUMBER;
    hash = (53 * hash) + getFrom();
    hash = (37 * hash) + TO_FIELD_NUMBER;
    hash = (53 * hash) + getTo();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.channel.api.proto.pub.coreapi.model.TimeRange parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.model.TimeRange parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.TimeRange parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.model.TimeRange parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.TimeRange parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.channel.api.proto.pub.coreapi.model.TimeRange parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.TimeRange parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.model.TimeRange parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.channel.api.proto.pub.coreapi.model.TimeRange parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.channel.api.proto.pub.coreapi.model.TimeRange parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.channel.api.proto.pub.coreapi.model.TimeRange parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.channel.api.proto.pub.coreapi.model.TimeRange parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.channel.api.proto.pub.coreapi.model.TimeRange prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * TimeRange represents a recurring weekly time window used for scheduling
   * (e.g. operating hours). Defined by selected days and a minute-of-day range.
   * </pre>
   *
   * Protobuf type {@code coreapi.model.TimeRange}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coreapi.model.TimeRange)
      io.channel.api.proto.pub.coreapi.model.TimeRangeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.channel.api.proto.pub.coreapi.model.TimeRangeOuterClass.internal_static_coreapi_model_TimeRange_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.channel.api.proto.pub.coreapi.model.TimeRangeOuterClass.internal_static_coreapi_model_TimeRange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.channel.api.proto.pub.coreapi.model.TimeRange.class, io.channel.api.proto.pub.coreapi.model.TimeRange.Builder.class);
    }

    // Construct using io.channel.api.proto.pub.coreapi.model.TimeRange.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      dayOfWeeks_ = emptyIntList();
      from_ = 0;
      to_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.channel.api.proto.pub.coreapi.model.TimeRangeOuterClass.internal_static_coreapi_model_TimeRange_descriptor;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.TimeRange getDefaultInstanceForType() {
      return io.channel.api.proto.pub.coreapi.model.TimeRange.getDefaultInstance();
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.TimeRange build() {
      io.channel.api.proto.pub.coreapi.model.TimeRange result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.channel.api.proto.pub.coreapi.model.TimeRange buildPartial() {
      io.channel.api.proto.pub.coreapi.model.TimeRange result = new io.channel.api.proto.pub.coreapi.model.TimeRange(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.channel.api.proto.pub.coreapi.model.TimeRange result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        dayOfWeeks_.makeImmutable();
        result.dayOfWeeks_ = dayOfWeeks_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.from_ = from_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.to_ = to_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.channel.api.proto.pub.coreapi.model.TimeRange) {
        return mergeFrom((io.channel.api.proto.pub.coreapi.model.TimeRange)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.channel.api.proto.pub.coreapi.model.TimeRange other) {
      if (other == io.channel.api.proto.pub.coreapi.model.TimeRange.getDefaultInstance()) return this;
      if (!other.dayOfWeeks_.isEmpty()) {
        if (dayOfWeeks_.isEmpty()) {
          dayOfWeeks_ = other.dayOfWeeks_;
          dayOfWeeks_.makeImmutable();
          bitField0_ |= 0x00000001;
        } else {
          ensureDayOfWeeksIsMutable();
          dayOfWeeks_.addAll(other.dayOfWeeks_);
        }
        onChanged();
      }
      if (other.getFrom() != 0) {
        setFrom(other.getFrom());
      }
      if (other.getTo() != 0) {
        setTo(other.getTo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int tmpRaw = input.readEnum();
              ensureDayOfWeeksIsMutable();
              dayOfWeeks_.addInt(tmpRaw);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureDayOfWeeksIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                dayOfWeeks_.addInt(input.readEnum());
              }
              input.popLimit(limit);
              break;
            } // case 10
            case 16: {
              from_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              to_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.IntList dayOfWeeks_ = emptyIntList();
    private void ensureDayOfWeeksIsMutable() {
      if (!dayOfWeeks_.isModifiable()) {
        dayOfWeeks_ = makeMutableCopy(dayOfWeeks_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * Days of the week this time range applies to.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinItems=1
     * no-example: repeated enum (DayOfWeek); OpenAPI array-example emission not yet supported by harness (iter5 abstention)
     * </pre>
     *
     * <code>repeated .coreapi.model.TimeRange.DayOfWeek day_of_weeks = 1 [json_name = "dayOfWeeks", (.buf.validate.field) = { ... }</code>
     * @return A list containing the dayOfWeeks.
     */
    public java.util.List<io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek> getDayOfWeeksList() {
      return new com.google.protobuf.Internal.IntListAdapter<
          io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek>(dayOfWeeks_, dayOfWeeks_converter_);
    }
    /**
     * <pre>
     * Days of the week this time range applies to.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinItems=1
     * no-example: repeated enum (DayOfWeek); OpenAPI array-example emission not yet supported by harness (iter5 abstention)
     * </pre>
     *
     * <code>repeated .coreapi.model.TimeRange.DayOfWeek day_of_weeks = 1 [json_name = "dayOfWeeks", (.buf.validate.field) = { ... }</code>
     * @return The count of dayOfWeeks.
     */
    public int getDayOfWeeksCount() {
      return dayOfWeeks_.size();
    }
    /**
     * <pre>
     * Days of the week this time range applies to.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinItems=1
     * no-example: repeated enum (DayOfWeek); OpenAPI array-example emission not yet supported by harness (iter5 abstention)
     * </pre>
     *
     * <code>repeated .coreapi.model.TimeRange.DayOfWeek day_of_weeks = 1 [json_name = "dayOfWeeks", (.buf.validate.field) = { ... }</code>
     * @param index The index of the element to return.
     * @return The dayOfWeeks at the given index.
     */
    public io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek getDayOfWeeks(int index) {
      return dayOfWeeks_converter_.convert(dayOfWeeks_.getInt(index));
    }
    /**
     * <pre>
     * Days of the week this time range applies to.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinItems=1
     * no-example: repeated enum (DayOfWeek); OpenAPI array-example emission not yet supported by harness (iter5 abstention)
     * </pre>
     *
     * <code>repeated .coreapi.model.TimeRange.DayOfWeek day_of_weeks = 1 [json_name = "dayOfWeeks", (.buf.validate.field) = { ... }</code>
     * @param index The index to set the value at.
     * @param value The dayOfWeeks to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setDayOfWeeks(
        int index, io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDayOfWeeksIsMutable();
      dayOfWeeks_.setInt(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Days of the week this time range applies to.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinItems=1
     * no-example: repeated enum (DayOfWeek); OpenAPI array-example emission not yet supported by harness (iter5 abstention)
     * </pre>
     *
     * <code>repeated .coreapi.model.TimeRange.DayOfWeek day_of_weeks = 1 [json_name = "dayOfWeeks", (.buf.validate.field) = { ... }</code>
     * @param value The dayOfWeeks to add.
     * @return This builder for chaining.
     */
    public Builder addDayOfWeeks(io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDayOfWeeksIsMutable();
      dayOfWeeks_.addInt(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Days of the week this time range applies to.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinItems=1
     * no-example: repeated enum (DayOfWeek); OpenAPI array-example emission not yet supported by harness (iter5 abstention)
     * </pre>
     *
     * <code>repeated .coreapi.model.TimeRange.DayOfWeek day_of_weeks = 1 [json_name = "dayOfWeeks", (.buf.validate.field) = { ... }</code>
     * @param values The dayOfWeeks to add.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder addAllDayOfWeeks(
        java.lang.Iterable<? extends io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek> values) {
      ensureDayOfWeeksIsMutable();
      for (io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek value : values) {
        dayOfWeeks_.addInt(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Days of the week this time range applies to.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinItems=1
     * no-example: repeated enum (DayOfWeek); OpenAPI array-example emission not yet supported by harness (iter5 abstention)
     * </pre>
     *
     * <code>repeated .coreapi.model.TimeRange.DayOfWeek day_of_weeks = 1 [json_name = "dayOfWeeks", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearDayOfWeeks() {
      dayOfWeeks_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Days of the week this time range applies to.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinItems=1
     * no-example: repeated enum (DayOfWeek); OpenAPI array-example emission not yet supported by harness (iter5 abstention)
     * </pre>
     *
     * <code>repeated .coreapi.model.TimeRange.DayOfWeek day_of_weeks = 1 [json_name = "dayOfWeeks", (.buf.validate.field) = { ... }</code>
     * @return A list containing the enum numeric values on the wire for dayOfWeeks.
     */
    public java.util.List<java.lang.Integer>
    getDayOfWeeksValueList() {
      dayOfWeeks_.makeImmutable();
      return dayOfWeeks_;
    }
    /**
     * <pre>
     * Days of the week this time range applies to.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinItems=1
     * no-example: repeated enum (DayOfWeek); OpenAPI array-example emission not yet supported by harness (iter5 abstention)
     * </pre>
     *
     * <code>repeated .coreapi.model.TimeRange.DayOfWeek day_of_weeks = 1 [json_name = "dayOfWeeks", (.buf.validate.field) = { ... }</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of dayOfWeeks at the given index.
     */
    public int getDayOfWeeksValue(int index) {
      return dayOfWeeks_.getInt(index);
    }
    /**
     * <pre>
     * Days of the week this time range applies to.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinItems=1
     * no-example: repeated enum (DayOfWeek); OpenAPI array-example emission not yet supported by harness (iter5 abstention)
     * </pre>
     *
     * <code>repeated .coreapi.model.TimeRange.DayOfWeek day_of_weeks = 1 [json_name = "dayOfWeeks", (.buf.validate.field) = { ... }</code>
     * @param index The index to set the value at.
     * @param value The enum numeric value on the wire for dayOfWeeks to set.
     * @return This builder for chaining.
     */
    public Builder setDayOfWeeksValue(
        int index, int value) {
      ensureDayOfWeeksIsMutable();
      dayOfWeeks_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Days of the week this time range applies to.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinItems=1
     * no-example: repeated enum (DayOfWeek); OpenAPI array-example emission not yet supported by harness (iter5 abstention)
     * </pre>
     *
     * <code>repeated .coreapi.model.TimeRange.DayOfWeek day_of_weeks = 1 [json_name = "dayOfWeeks", (.buf.validate.field) = { ... }</code>
     * @param value The enum numeric value on the wire for dayOfWeeks to add.
     * @return This builder for chaining.
     */
    public Builder addDayOfWeeksValue(int value) {
      ensureDayOfWeeksIsMutable();
      dayOfWeeks_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Days of the week this time range applies to.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:MinItems=1
     * no-example: repeated enum (DayOfWeek); OpenAPI array-example emission not yet supported by harness (iter5 abstention)
     * </pre>
     *
     * <code>repeated .coreapi.model.TimeRange.DayOfWeek day_of_weeks = 1 [json_name = "dayOfWeeks", (.buf.validate.field) = { ... }</code>
     * @param values The enum numeric values on the wire for dayOfWeeks to add.
     * @return This builder for chaining.
     */
    public Builder addAllDayOfWeeksValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureDayOfWeeksIsMutable();
      for (int value : values) {
        dayOfWeeks_.addInt(value);
      }
      onChanged();
      return this;
    }

    private int from_ ;
    /**
     * <pre>
     * Start time as minutes from midnight. Must be less than `to`.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:Minimum=0
     * +kubebuilder:validation:Maximum=1440
     * +kubebuilder:example="540"
     * </pre>
     *
     * <code>int32 from = 2 [json_name = "from", (.buf.validate.field) = { ... }</code>
     * @return The from.
     */
    @java.lang.Override
    public int getFrom() {
      return from_;
    }
    /**
     * <pre>
     * Start time as minutes from midnight. Must be less than `to`.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:Minimum=0
     * +kubebuilder:validation:Maximum=1440
     * +kubebuilder:example="540"
     * </pre>
     *
     * <code>int32 from = 2 [json_name = "from", (.buf.validate.field) = { ... }</code>
     * @param value The from to set.
     * @return This builder for chaining.
     */
    public Builder setFrom(int value) {

      from_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Start time as minutes from midnight. Must be less than `to`.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:Minimum=0
     * +kubebuilder:validation:Maximum=1440
     * +kubebuilder:example="540"
     * </pre>
     *
     * <code>int32 from = 2 [json_name = "from", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearFrom() {
      bitField0_ = (bitField0_ & ~0x00000002);
      from_ = 0;
      onChanged();
      return this;
    }

    private int to_ ;
    /**
     * <pre>
     * End time as minutes from midnight. Must be greater than `from`.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:Minimum=0
     * +kubebuilder:validation:Maximum=1440
     * +kubebuilder:example="1080"
     * </pre>
     *
     * <code>int32 to = 3 [json_name = "to", (.buf.validate.field) = { ... }</code>
     * @return The to.
     */
    @java.lang.Override
    public int getTo() {
      return to_;
    }
    /**
     * <pre>
     * End time as minutes from midnight. Must be greater than `from`.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:Minimum=0
     * +kubebuilder:validation:Maximum=1440
     * +kubebuilder:example="1080"
     * </pre>
     *
     * <code>int32 to = 3 [json_name = "to", (.buf.validate.field) = { ... }</code>
     * @param value The to to set.
     * @return This builder for chaining.
     */
    public Builder setTo(int value) {

      to_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * End time as minutes from midnight. Must be greater than `from`.
     *
     * +kubebuilder:validation:Required
     * +kubebuilder:validation:Minimum=0
     * +kubebuilder:validation:Maximum=1440
     * +kubebuilder:example="1080"
     * </pre>
     *
     * <code>int32 to = 3 [json_name = "to", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearTo() {
      bitField0_ = (bitField0_ & ~0x00000004);
      to_ = 0;
      onChanged();
      return this;
    }

    /* Generated by protoc-gen-java-set-or-clear */
    
    /**
     * @param values The day_of_weeks to add.
     * @return This builder for chaining.
     */
    public Builder addAllOrClearDayOfWeeks(java.lang.Iterable<? extends io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek> values) {
    	if (values == null)
    		return clearDayOfWeeks();
    	else
    		return addAllDayOfWeeks(values);
    }
    	
    /**
     * @param values The values to map.
     * @param mapFunc The function to map the values into each proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapAllOrClearDayOfWeeks(java.lang.Iterable<T> values, java.util.function.Function<T, ? extends io.channel.api.proto.pub.coreapi.model.TimeRange.DayOfWeek> mapFunc) {
    	if (values == null)
    		return clearDayOfWeeks();
    	else {
    		values.forEach(value -> addDayOfWeeks(mapFunc.apply(value)));
    		return this;
    	}
    }
    	
    /**
     * @param value The from to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearFrom(java.lang.Integer value) {
    	if (value == null)
    		return clearFrom();
    	else
    		return setFrom(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearFrom(T value, java.util.function.Function<T, java.lang.Integer> mapFunc) {
    	if (value == null)
    		return clearFrom();
    	else
    		return setFrom(mapFunc.apply(value));
    }
    	
    /**
     * @param value The to to set.
     * @return This builder for chaining.
     */
    public Builder setOrClearTo(java.lang.Integer value) {
    	if (value == null)
    		return clearTo();
    	else
    		return setTo(value);
    }
    	
    /**
     * @param value The value to map.
     * @param mapFunc The function to map the value into the proto message.
     * @return This builder for chaining.
     */
    public <T> Builder mapOrClearTo(T value, java.util.function.Function<T, java.lang.Integer> mapFunc) {
    	if (value == null)
    		return clearTo();
    	else
    		return setTo(mapFunc.apply(value));
    }
    	
    // @@protoc_insertion_point(builder_scope:coreapi.model.TimeRange)
  }

  // @@protoc_insertion_point(class_scope:coreapi.model.TimeRange)
  private static final io.channel.api.proto.pub.coreapi.model.TimeRange DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.channel.api.proto.pub.coreapi.model.TimeRange();
  }

  public static io.channel.api.proto.pub.coreapi.model.TimeRange getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TimeRange>
      PARSER = new com.google.protobuf.AbstractParser<TimeRange>() {
    @java.lang.Override
    public TimeRange parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TimeRange> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TimeRange> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.channel.api.proto.pub.coreapi.model.TimeRange getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
