// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coreapi/model/webhook.proto

package io.channel.api.proto.pub.coreapi.model;

public final class WebhookOuterClass {
  private WebhookOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coreapi_model_Webhook_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coreapi_model_Webhook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033coreapi/model/webhook.proto\022\rcoreapi.m" +
      "odel\032\033buf/validate/validate.proto\032\037googl" +
      "e/protobuf/timestamp.proto\"\346\002\n\007Webhook\022\016" +
      "\n\002id\030\001 \001(\tR\002id\022\035\n\nchannel_id\030\002 \001(\tR\tchan" +
      "nelId\022\032\n\004name\030\003 \001(\tB\006\272H\003\310\001\001R\004name\022\030\n\003url" +
      "\030\004 \001(\tB\006\272H\003\310\001\001R\003url\022\024\n\005token\030\005 \001(\tR\005toke" +
      "n\0229\n\ncreated_at\030\006 \001(\0132\032.google.protobuf." +
      "TimestampR\tcreatedAt\022\036\n\006scopes\030\007 \003(\tB\006\272H" +
      "\003\310\001\001R\006scopes\022\'\n\013api_version\030\010 \001(\tB\006\272H\003\310\001" +
      "\001R\napiVersion\022B\n\017last_blocked_at\030\t \001(\0132\032" +
      ".google.protobuf.TimestampR\rlastBlockedA" +
      "t\022\030\n\007blocked\030\n \001(\010R\007blockedBb\n&io.channe" +
      "l.api.proto.pub.coreapi.modelP\001Z6github." +
      "com/channel-io/ch-proto-public/coreapi/g" +
      "o/modelb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_coreapi_model_Webhook_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_coreapi_model_Webhook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coreapi_model_Webhook_descriptor,
        new java.lang.String[] { "Id", "ChannelId", "Name", "Url", "Token", "CreatedAt", "Scopes", "ApiVersion", "LastBlockedAt", "Blocked", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
